### PR TITLE
fix: decimal in amount and remove decimal from phone number in send

### LINKED ISSUE #332: Amount doesnt accept decimal and Phone number can be decimal in Send
**Summary:**

Amount doesnt accept decimal and Phone number can be decimal in Send, which is logically wrong and might lead to bugs.

**Steps to reproduce:**

Send Fragment -> amount -> phone no
videotogif_2019 02 21_07 56 02

### PR DESCRIPTION
**Pull request by shiv07tiwari**
Fixes #332 

Please Add Screenshots If any UI changes.
videotogif_2019 02 21_07 57 59

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by shiv07tiwari** [comment]
@luckyman20 Kindly review.

**Comment by luckyman20** [comment]
We would allow up to two decimal digits only.

**Comment by shiv07tiwari** [comment]
Okay I'll add the limit in amount part.

**Comment by shiv07tiwari** [comment]
@luckyman20 Made the changes.

**Comment by shaliniv16** [comment]
@shiv07tiwari @luckyman20 I already open these issues in #318 and #296. I am working on it.

**Pull request closed without merging**
