### PR TITLE
Add Mifos Pay logo in Passcode Section

### LINKED ISSUE #883: Add official logo in Passcode section
**Summary:**
Currently, there was no official logo visible in the Passcode section while login , entering or setting the passcode.

### PR DESCRIPTION
**Pull request by refactor-droidyy**
## Issue Fix
Fixes #883 

## Screenshots

Screenshot_2020-04-10-11-46-00-716_org mifos mobilewallet mifospay

## Description
Added logo of the app in the Passcode Section.
##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Bhavnaharitsa** [comment]
@refactor-droidyy Do we need this?

**Comment by refactor-droidyy** [comment]
@Bhavnaharitsa since now we have the official logo and in passcode section there is option for incorporating the logo so I think we need this...

**Comment by dubeyaayush07** [comment]
@refactor-droidyy Maybe we can increase the size of the image as currently I looks a bit out proportion

**Comment by rachittt** [comment]
I don't think we need a logo here. Looks out of place.

**Pull request closed without merging**
