### PR TITLE
fix:taking two clicks to switch between Mobile Number and VPA in Sele…

### LINKED ISSUE #263: Redesign: It's taking two clicks to switch between Mobile Number and VPA in Select transfer method
**Summary:**

Redesign: It's taking two clicks to switch between Mobile Number and VPA in Select transfer method, this problem occurs in the second time.

**Steps to reproduce:**

- Go to Payments Activity
- Click on Mobile Number
- Click on VPA
- Again click on Mobile Number

**Expected behavior:**

It should open Mobile Number option.

**Observed behavior:**

Nothing happen. We have to click again to open Mobile Number option.

**Device and Android version:**

Realme 2 Pro
Android version 8.1.0

### PR DESCRIPTION
**Pull request by shaliniv16**
Fixes #263 

**Gif:**

videotogif_2019 03 02_19 05 33

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

### CODE REVIEW

**Comment by ankurs287** [comment]
@shaliniv16 upload the gif.

**Comment by shaliniv16** [comment]
@ankurs287 uploaded.

**Comment by rachittt** [comment]
@shaliniv16 your PR does not fix the issue. 

If you add an amount in VPA/Mobile Number, you will again have to click twice to switch between them. Please fix it.

**Comment by shiv07tiwari** [comment]
@shaliniv16 This issue is already fixed.

**Pull request closed without merging**
