### PR TITLE
Colour Change Completed as per the website

### PR DESCRIPTION
**Pull request by shahidtumbi**
## Issue Fix
Fixes #{Issue Number}

##

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by haran2248** [comment]
Please add the screenshots

**Comment by haran2248** [comment]
And create and link PRs to those issues

**Comment by haran2248** [comment]
Change the commits,follow PR guidelines and squash the commits :)

**Comment by devansh-299** [comment]
@shahidtumbi can you link the related issue or explain the problem being addressed in detail?

**Comment by devansh-299** [comment]
Closing this because of inactivity. Although @shahidtumbi we can re-open this pull request if you want

**Pull request closed without merging**
