### PR TITLE
fix: dark theme colors

### PR DESCRIPTION
**Pull request by Nagarjuna0033**
## Issue Fix
Fixes #{Issue Number}
Jira Task: [Task_Number](Task_Link)

## Screenshots

| Light theme | Dark theme | Before |
|-------------|------------|--------|
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  |  |
|  |  | |

##

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by itsPronay** [comment]
image
@Nagarjuna0033 for edit icon, tint black

**Comment by Nagarjuna0033** [comment]
> image @Nagarjuna0033 for edit icon, tint black

Ok I will change

**Comment by therajanmaurya** [comment]
Let me know once done!

**Comment by Nagarjuna0033** [comment]
> Let me know once done!

Done sir

**Review by itsPronay — COMMENTED** [review]
image
one little change, we should change the color of `walletCard` for dark theme

**Pull request merged**
