### PR TITLE
feat: Added Internet connection check in Login and Registration activities

### LINKED ISSUE #537: Check internet connection while registering and logging in the app
**Summary:**

While Registering and logging into the app without an internet connection, the application is simply displaying a toast showing "Error logging in " in Login activity and "Error" in Registration activity. It must alert the user displaying the toast message showing "**No internet Connection**".

**Steps to reproduce:**

Try registering and logging into the app without Internet Connection.

**Expected behavior:**

It must alert the user with toasts messages showing "**No Internet Connection**"

**Observed behavior:**

No internet connection toasts are missing.

**Device and Android version:**

Device: Samsung Galaxy s5
Version: 6.0.1

**Screenshots:**

**Login Activity:**

Screenshot_2019-04-16-20-20-45

**Registration Activity:**

Screenshot_2019-04-18-17-50-45

### PR DESCRIPTION
**Pull request by RajaVamsi11**
Fixes #537 

Please Add Screenshots If any UI changes.

**Login Activity:**

Screenshot_2019-04-18-17-38-17

**Registration Activity:**

Screenshot_2019-04-18-18-44-06

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by RajaVamsi11** [comment]
@naman14 @luckyman20 Can you please review this issue?

**Review by shiv07tiwari — COMMENTED** [review]
@RajaVamsi11 I guess this is not very important. Error in LogIn justifies all the stuff.

**Review by ghost — CHANGES_REQUESTED** [review]
In SignupActivity, call the overridden onRegisterFail function rather than writing your own two lines.
@RajaVamsi11 also handle the conflicts properly first.

**Comment by rchtgpt** [comment]
Closing this because of inactivity.

**Pull request closed without merging**
