### PR TITLE
feat: common function for all dialog boxes

### LINKED ISSUE #616: A utility function for all the DialogBoxes
**GCI TASK**
The app requires a lot of confirmation and dialog boxes, which is causing a lot of repeated code throughout the codebase.
The task is to make a common function for all these dialog boxes, maybe in the utility function.
It is up to you how efficiently you can manage to get things done.

### PR DESCRIPTION
**Pull request by laxyapahuja**
## Issue Fix
Fixes #616

## Description 
Made a utility class that can be called anywhere to make an Alert Dialog with less amount of code. Also replaced the alertDialog in one activity ```EditProfileActivity``` with the new utility class.

##
- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by luckyman20** [comment]
Push to `dev`

**Comment by laxyapahuja** [comment]
> Push to `dev`

Hey, I just changed the base branch from ```master``` to ```dev``` and I'm seeing a lot of extra commits. How to go on about this?

**Comment by Bhavnaharitsa** [comment]
I guess you are getting some conflicting files

**Comment by rachittt** [comment]
hey @laxyapahuja , it's probably because you created the branch `laxyapahuja:dialogbox` on top of the master branch. It should be created on top of `laxyapahuja:dev` branch. Kindly check 😃

**Pull request closed without merging**
