### PR TITLE
added logo in passcode activity

### LINKED ISSUE #723: feat : Add mifos logo in passcode activity
**Summary:**

Add mifos logo in passcode activity

**Steps to reproduce:**

**Expected behavior:**

**Observed behavior:**

**Device and Android version:**

Motorola one vision 
Android Q ( version 10)

**Screenshots:**
Before
Screenshot_20200217-122518
After
Screenshot_20200217-122808

### PR DESCRIPTION
**Pull request by indracs97**
Fixes #723 

Please Add Screenshots If any UI changes.

Added the mifos_logo in the passcode activity

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Bhavnaharitsa** [comment]
@indracs97 Add the screen shot of the change
And also, do we need a logo here?

**Comment by indracs97** [comment]
I added a screenshot in the issue #723. Also, in the passcode activity, there was a function that enabled us to add a drawable above the pin so, I guess it was planned beforehand.

**Comment by Bhavnaharitsa** [comment]
@indracs97 I meant the screen shot of the changes you made, not the issue. And also, we already have a logo in the front page, not needed again in passcode activity. 
Anyway contact the mentors

**Comment by luckyman20** [comment]
@indracs97 Thank you for the PR but we are still to decide an official logo just for this app which we would use throughout the app.

**Pull request closed without merging**
