### PR TITLE
 fix: added scroll bars in each of the layouts

### LINKED ISSUE #488: Scroll bar is missing in Transactions History and Other Bank Screen.
**Summary:**

Presently there is no scroll bar in Transactions History and Other Bank Screen.

### PR DESCRIPTION
**Pull request by Bhavnaharitsa**
Fixes #488 
Added scroll bars wherever needed 

- [.] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [.] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [.] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Bhavnaharitsa** [comment]
@luckyman20 please review

**Comment by laxyapahuja** [comment]
Already solved in #489

**Comment by Bhavnaharitsa** [comment]
Yes but issue is unreffered and hence I took it up
@laxyapahuja

**Comment by Bhavnaharitsa** [comment]
@luckyman20 Sir, we dont have scroll bars in these activities.
If this issue is in reference, can I take this up?

**Comment by luckyman20** [comment]
@Bhavnaharitsa Open a new issue and specify the activities along with screenshots.

**Comment by Bhavnaharitsa** [comment]
@luckyman20 Yes sir, sure!

**Pull request closed without merging**
