### PR TITLE
 changed blunt id names to senseful id names

### LINKED ISSUE #706: fix: senseless names for ids in activity_login
**Summary:**
<TextView
            android:id="@+id/textView2"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="0dp"
            android:layout_marginLeft="0dp"
            android:layout_marginEnd="@dimen/marginBetweenWords"
            android:layout_marginRight="@dimen/marginBetweenWords"
            android:text="@string/don_t_have_an_account"
            android:textColor="@color/colorTextSecondary" />

       <TextView
            android:id="@+id/textView"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/create_one"
            android:textColor="@color/colorAccent" />

These views have senseless ids and ids could be changed according to it's purpose.

### PR DESCRIPTION
**Pull request by Bhavnaharitsa**
Fixes #706 
Added senseful names to id in activity_login page

- [.] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [.] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [.] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Bhavnaharitsa** [comment]
@luckyman20 Please review

**Comment by Bhavnaharitsa** [comment]
@naman14 Review this

**Comment by Bhavnaharitsa** [comment]
@naman14 @luckyman20 Sir, please review this

**Comment by naman14** [comment]
since we are not using the ids for these view, can remove them. Also, i am sure a lot of views throughout the app would have blunt ids , maybe also fix them. Else someone else will create another PR later on.

**Comment by Bhavnaharitsa** [comment]
> since we are not using the ids for these view, can remove them. Also, a lot of views throughout the app would have blunt ids , maybe also fix them in this PR itself. Else someone else will create another PR later on.

I shall do it  :)

**Comment by rachittt** [comment]
@Bhavnaharitsa are you still working on it?

**Comment by Bhavnaharitsa** [comment]
@rachittt yes

**Comment by rchtgpt** [comment]
This PR is from an unknown repository, hence no more work can be done on this. therefore, closing it.

**Pull request closed without merging**
