### PR TITLE
Documentation: Git Bash Travis CI commands in README.md

### LINKED ISSUE #910: Typo: Travis CI commands in README.md
**Summary:**

Travis CI commands in the [README.md](https://github.com/openMF/mobile-wallet#travis-ci) file are not entirely correct.

**Expected behavior:**

the commands should be correct according to each Operating System.

### PR DESCRIPTION
**Pull request by haran2248**
## Issue Fix
Fixes #910 

## Screenshots

WhatsApp Image 2020-07-22 at 17 41 48

## Description

The readme of `gradlew` has been fixed to `./gradlew`.

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by haran2248** [comment]
In windows only './gradlew build' works 'gradlew' alone will not work.The commands have been run in git bash
WhatsApp Image 2020-07-22 at 23 22 10 (1)
WhatsApp Image 2020-07-22 at 23 22 10

**Review by devansh-299 — APPROVED** [review]
LGTM thanks for the pull request @haran2248

**Comment by Bhavnaharitsa** [comment]
@haran2248 Good work on the PR. Looks good to me :)

**Comment by haran2248** [comment]
Thank you @Bhavnaharitsa @devansh-299

**Comment by devansh-299** [comment]
Closing this PR as the source repository has been deleted

**Pull request closed without merging**
