### PR TITLE
Fix#149 Added the missing code for showToaster method

### LINKED ISSUE #149: Toast message should appear if PIN is wrong
**Summary:**
A toast message should be shown if the entered PIN is wrong while logging after successfully setting up the PIN

**Steps to reproduce:**
Set up Login Through PIN and open the App. Add a wrong PIN

**Expected behavior:**
A toast should be shown saying that the entered PIN is wrong

**Device and Android version:**
OnePlus 5 
Android Oreo 8.1

### PR DESCRIPTION
**Pull request by codepoet2017390**
**Fixes #149** 

Please Add Screenshots If any UI changes.
screenshot_20181217-124036

**Please Add Summary of what changes you have made.(Optional)**
Added the missing code to the show Toaster method in Passcode Activity.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by luckyman20** [comment]
@codepoet2017390 Fix the travis error.

**Comment by codepoet2017390** [comment]
@luckyman20  i just added a Toast message what could be the possible reason for Travis Failure?

**Comment by luckyman20** [comment]
@codepoet2017390 Here is the error which is failing travis -

`:mifospay:checkstyle[ant:checkstyle] /home/travis/build/openMF/mobile-wallet/mifospay/src/main/java/org/mifos/mobilewallet/mifospay/passcode/ui/PassCodeActivity.java:76:48: ',' is not followed by whitespace.
[ant:checkstyle] /home/travis/build/openMF/mobile-wallet/mifospay/src/main/java/org/mifos/mobilewallet/mifospay/passcode/ui/PassCodeActivity.java:76:61: ',' is not followed by whitespace.`

**Comment by luckyman20** [comment]
@codepoet2017390 Please squash the commits.

**Comment by codepoet2017390** [comment]
@luckyman20  updated

**Pull request merged**
