### PR TITLE
fix : #1148 fixing warnings in xml files

### LINKED ISSUE #1148: Fixing warnings in xml files
**Summary:**

There are warnings in xml files like - 

- [ ] Image without contentDescription
- [ ] Hardcoded strings
- [ ] ScrollView size validation

### PR DESCRIPTION
**Pull request by Harshad09**
## Issue Fix
Fixes #1148

## Description
Fixing issues like  Image without contentDescription by adding image content description, fixing orientation, adding string values over hardcode values.

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by haran2248** [comment]
Squash the commits together

**Comment by Harshad09** [comment]
@devansh-299  @s-ayush2903 Can you Please Review my PR

**Comment by Harshad09** [comment]
> Squash the commits together

okay sure

**Comment by divyank00** [comment]
I feel this is really not a mandatory thing right now? Any thoughts @devansh-299

**Comment by Harshad09** [comment]
> I feel this is really not a mandatory thing right now? Any thoughts @devansh-299

In the pr I tried to fix some warnings which include hardcoded string at one or two places, use of dp instead of sp for text size, and mostly 'Missing `contentDescription `attribute on image' in XML. It's for the Accessibility Features of Android. The `contentDescription `is what gets read back to the (assumingly blind or hard-of-sight user) so they have an idea of what the picture is since they aren't able to view it. So for contentDescription we have three choices,

1. We can add a `contentDescription`
2. We can ignore it by using `tools:ignore="ContentDescription"` 
3. We can set null `android:contentDescription="@null"`

**Pull request closed without merging**
