### PR TITLE
fix: added logo in the top of app title

### LINKED ISSUE #699: Feat: Add logo of app on Main screen
**Summary:**

We dont our app logo in the top of Mifos Pay. That makes the UI blant. We should have our logo in our main screen

Screenshot_20200205-083845_Mifos Pay

### PR DESCRIPTION
**Pull request by Bhavnaharitsa**
Fixes #699
Added logo of the app on the main screen that is login activity
page

- [.] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [.] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [.] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by rachittt** [comment]
We do not have an official logo for Mifos Pay yet. I think we can wait until a logo gets finalized.

**Comment by Bhavnaharitsa** [comment]
@rachittt We do have. Isnt that the one?

**Comment by rachittt** [comment]
> @rachittt We do have. Isnt that the one?

that is the logo of the Mifos Initiative. not the Mifos Pay mobile app.

**Comment by Bhavnaharitsa** [comment]
> @rachittt We do have. Isnt that the one?
> 
> that is the logo of the Mifos Initiative. not the Mifos Pay mobile app.

Oh, I didn't know that. I got confused

**Comment by naman14** [comment]
Th constraints are not correct and the image is not constrained properly anywhere.

Add marginTop and constraint top, left, right to oarent

**Comment by Bhavnaharitsa** [comment]
@naman14 The logo is not the correct one, anyway

**Comment by naman14** [comment]
The logo is fine, we don't have any other logo for the app.

**Comment by Bhavnaharitsa** [comment]
> The logo is fine, we don't have any other logo for the app.

Okay fine, let me make the layout corrections then

**Comment by Bhavnaharitsa** [comment]
@naman14 @luckyman20 Please review now!

**Pull request merged**
