### PR TITLE
refactor : Added dependencies version in root project

### LINKED ISSUE #266: Minor gradle refactor
**Summary:**
In Gradle, versions of some dependency are mentioned directly but according to the convention it should be fetched from rootProject.

**Expected behavior:**
Dependencies version must be fetched fron root project.

**Observed behavior:**
Versions of dependencies are directly mentioned in gradle files.

### PR DESCRIPTION
**Pull request by RajaVamsi11**
Fixes #266 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by RajaVamsi11** [comment]
@naman14 @ankurs287 Can you please review this PR.

**Comment by RajaVamsi11** [comment]
@luckyman20 Can you please review this PR.

**Comment by naman14** [comment]
@RajaVamsi11 Most dependencies are specific to `mifospay` module so it doesn't make sense to define those dependencies in root project. Only keep common dependencies of `mifospay` and `core` in root project and keep the specific dependencies in respective `build.gradle` files

**Comment by RajaVamsi11** [comment]
@naman14  Updated according to the changes suggested. Can you please review once.

**Pull request merged**
