### PR TITLE
Fixes: #242 App Crash while Registering

### LINKED ISSUE #242: App crashes while registering user
**Summary:**

App crashes when registering in app. 

**Steps to reproduce:**

Click on create one (dont have an account, create one) button on login page 

**Expected behavior:**

Successfully register user.

**Observed behavior:**

App crashes

**Device and Android version:**

Redmi 3S Prime, Android 6

**Screenshots:**

Nil. App crashes on login screen.

### PR DESCRIPTION
**Pull request by ThisIsNSH**
Fixes #242 

### Please Add Screenshots If any UI changes. 
Nil

### Please Add Summary of what changes you have made.(Optional)
The issue was in activity_mobile_verification.xml. It had app:backgroundTint & android:backgroundTint at the same time. Removing android:backgroundTint resolved the bug. 

### Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by ThisIsNSH** [comment]
@luckyman20 please review

**Comment by luckyman20** [comment]
@ThisIsNSH Please add GIF to show the changes.

**Comment by RajaVamsi11** [comment]
@luckyman20 @ThisIsNSH Can I work on this issue as it is inactive for more than one month.

**Comment by luckyman20** [comment]
@ThisIsNSH A week's time is given to you to respond on this PR otherwise it will be closed. I hope that is fair enough.

**Comment by RajaVamsi11** [comment]
@luckyman20 Can I work on this issue as @ThisIsNSH is inactive.

**Pull request closed without merging**
