### PR TITLE
fix: #791 Added scrollers to history fragment

### LINKED ISSUE #791: feat:  Scroll to Bottom in History Fragment
**Description**

If there is a large amount of transaction history available the user wants to look for a previous transaction then he needs to scroll a lot of times, what if there is an option or icon for the same this would be very useful in our app.

### PR DESCRIPTION
**Pull request by divyank00**
## Issue Fix
Fixes #791 #812

## Screenshots

https://user-images.githubusercontent.com/50913976/104511131-490e3500-5612-11eb-867d-a7ad3f20fdc1.mp4

## Description
Added a scroller in history fragment to scroll up and down

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by divyank00** [comment]
@devansh-299 Can you please review this

**Comment by Harshad09** [comment]
I guess this feature is already covered in #960 pull request, @devansh-299 any views?

**Comment by Harshad09** [comment]
I guess this feature is already covered by the #960 pull request.

**Comment by divyank00** [comment]
> I guess this feature is already covered by the #960 pull request.

That was not merged due to conflicts. Just check if the thread has some issues😊

**Comment by divyank00** [comment]
@devansh-299 Can you please review this

**Pull request closed without merging**
