### PR TITLE
Fix #786 - added option to share receipt deeplink

### LINKED ISSUE #786: Feat: add an option to share transaction receipt deeplink
**Summary:**
Currently clicking the receipt link just copies it to the clipboard I think it will be better if we give the user option to share this link (which will include copying it to the clipboard).

### PR DESCRIPTION
**Pull request by dubeyaayush07**
Fix #786

Screenrecorder-2020-03-02-22-18

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by shiv07tiwari** [comment]
It is already providing the option to copy. Is it really necessary to add a whole share system?

**Comment by dubeyaayush07** [comment]
The main purpose of the deeplink is to share it so that the users with same application can open it so by cutting out the in between process of copying it I thought the users can share the deeplink directly also the share menu provides an option to copy it

**Comment by shiv07tiwari** [comment]
@dubeyaayush07 Please resolve the merge conflict. This PR will be merged as soon as you fix this.

**Comment by dubeyaayush07** [comment]
@shiv07tiwari done

**Pull request closed without merging**
