### PR TITLE
Fix #610 - Fixes UI inconsistencies in the sign up activity

### LINKED ISSUE #610: UI inconsistencies in the sign up activity
**Summary:**
As I was using the app I found multiple problems in the sign up activity :
- There is no way to toggle between seeing your password and hiding it
- address line 2 should not be mandatory (for example If you live in a house at 623 Elm Street, you will not need Address Line 2 at all)

**Steps to reproduce:**
open the app>click create one>click sign up as merchant or as customer>choose google account >validate mobile phone>:
- type your password
- fill out all the forms except the address line 2 and click next (you'll see an error message)

**Expected behavior:**
- the user should be able to toggle between viewing and hiding his password
- the user should be able to dismiss address line 2

**Observed behavior:**
- the user is not able to toggle between viewing and hiding his password
- the user is not able to dismiss address line 2

**Device and Android version:**

Device: Condor A8
Android version : 8.0
**Screenshots:**

### PR DESCRIPTION
**Pull request by OussEmaDevCode**
Fixes #610 

Please Add Screenshots If any UI changes.
 address line 2 is empty Screenshot_20191219-152255

 video2gif_20191219_152402

Please Add Summary of what changes you have made.(Optional)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by OussEmaDevCode** [comment]
@luckyman20 Hi : ), Please have a look !!

**Comment by OussEmaDevCode** [comment]
@shiv07tiwari is it going to be merged ?

**Comment by shiv07tiwari** [comment]
@OussEmaDevCode Please attach a GIF (testing all the feats), so that we are sure that it is working.

**Comment by OussEmaDevCode** [comment]
@shiv07tiwari [here](https://photos.app.goo.gl/NMyi1XMPHqEWLv669) you go !! I wasn't able to upload it to github, the file was too big.

**Pull request merged**
