### PR TITLE
fix: layout on signup screen

### LINKED ISSUE #571: Layout Change in Signup Screen
**Summary:**
1. Resizing the `TextInputEditText` 
2. Changing the color of back button  
3. Resizing the control being used for selecting country

**Steps to reproduce:**
Open the app and click "Create One" textview located at bottom.

**Expected behavior:**
edited
Please ignore the background as this is an edited screenshot of app to represent the idea.

**Observed behavior:**
original

**Device and Android version:**
All devices

**Screenshots:**
Attached above.

### PR DESCRIPTION
**Pull request by akkywadhwa**
Fixes #571 
ezgif com-video-to-gif(5)

- [X] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [X] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [X] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by shiv07tiwari — COMMENTED** [review]
@akkywadhwa Nice work!
@luckyman20 Do we really need two screens only for OTP verification? It's a small part of the whole app and given that it's a utility-based application, this doesn't look very appealing to me. Thoughts?
Also, if we are going with this design, is it necessary to make a whole new activity for this? It's a small job relatively, and we should try to keep this as light as possible.
Would love to hear your suggestions @naman14 @luckyman20

**Comment by luckyman20** [comment]
@shiv07tiwari Yes, I really think that we should have two separate screens for mobile number and OTP as most of the apps have. Also, I do agree on the point that we shouldn't make a whole new activity for taking OTP. @akkywadhwa Please look into and resolve that.

**Comment by devansh-299** [comment]
@shiv07tiwari @luckyman20 @akkywadhwa There has been no update on this PR from a long time. Should we close this?

**Comment by shiv07tiwari** [comment]
@akkywadhwa We are considering the redesign for this activity and your PR looks good. Kindly make the suggested changes, hopefully within a week as we need to fix this asap.

**Comment by luckyman20** [comment]
Closing this because of inactivity.

**Pull request closed without merging**
