### PR TITLE
Update SDK versions

### LINKED ISSUE #217: Increase the compile and target SDK version
**Summary:**
The compileSdkVersion and targetSdkVersion which are set to versions 26 and 26, respectively, must be changed to 28( Android Pie)  as the latest Android APIs must be used to make use of the latest features. 

@luckyman20 @ankurs287 Can you please review this issue? I will fix this.

### PR DESCRIPTION
**Pull request by RajaVamsi11**
Changes: Updated compile and target SDK version of the app.

Fixes #217

### CODE REVIEW

**Comment by codepoet2017390** [comment]
please route it to dev branch

**Comment by RajaVamsi11** [comment]
@luckyman20 Please review this issue?

**Comment by luckyman20** [comment]
I think you had some issues with your local branch that's why you are sending previous commits too. Please rectify this.

**Comment by codepoet2017390** [comment]
Stash your commits

**Comment by RajaVamsi11** [comment]
Those two commits are made from two different accounts accidentally. Therefore they cannot be squashed.Its my mistake and it will not happen in future.

**Comment by RajaVamsi11** [comment]
@luckyman20 As these two commits can not be squashed, I am closing this PR and creating another one.

**Pull request closed without merging**
