### PR TITLE
 added dependency

### LINKED ISSUE #566: Lacking dependency
**Summary:**

The Request Fragment uses a third party library for Phone number and Number Exception but initially the library is missing in gradle file and a new contributor has to manually add it. 

**Steps to reproduce:**

Simple fork and clone

**Expected behavior:**

Clean build

**Observed behavior:**

Error in RequestFragment.java

**Device and Android version:**

Samsung J8

**Would you be working on this issue?**
Yes

### PR DESCRIPTION
**Pull request by Bhavnaharitsa**
Fixes #566 

I added the dependency and now it works fine

- [.] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [.] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [.] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by jsahil730** [comment]
Why is this PR not being merged? @vorburger @edcable @vishwasbabu @Nayan

**Comment by vorburger** [comment]
@jsahil730 I don't maintain this project (repo), I'm only helping with the main https://github.com/apache/fineract backend.

But with 97 pending PRs, this clearly needs more active maintainers willing to review PRs etc. If you would like to be one of them, perhaps you should be granted commit privileges to help here... would you be interested?

**Comment by jsahil730** [comment]
> @jsahil730 I don't maintain this project (repo), I'm only helping with the main https://github.com/apache/fineract backend.
> 
> But with 97 pending PRs, this clearly needs more active maintainers willing to review PRs etc. If you would like to be one of them, perhaps you should be granted commit privileges to help here... would you be interested?

Sure, I'd love to. I am honored :).

**Comment by vorburger** [comment]
@jsahil730 may be before doing that, let me reach out to some old friends how we could improve the situation here... in the mean time, would you like to review some other PRs, and either comment with "LGTM" on them if you think they should be merged, or provide review feedback?

@luckyman20 I can see that you've recently merged PRs in this repo - are you interested in reviewing e.g. this, and other PRs, to help reduce the "PR backlog" this project has?

**Comment by vorburger** [comment]
Actually, if I was more involved in this project (but I'm not...), could I suggest that BEFORE anyone merges any of the 97 pending pull requests, someone first, before doing anything else for this project here, raises a PR to get the Travis CI build to pass again? It's currently broken, see #573.

**Comment by Bhavnaharitsa** [comment]
Dear @vorburger @edcable @vishwasbabu @Nayan 
When I cloned the project, this particular dependency was missing. I had to add it manually and then the build/gradle run fine. 
So, I thought I should take this up as an issue(though very small)  because the lacking of this dependency shows errors in some errors.
Kindly review it :)

**Comment by luckyman20** [comment]
@Bhavnaharitsa thank you for your contributions

**Pull request closed without merging**
