### PR TITLE
feat: Missing pop-up message in Complete KYC

### LINKED ISSUE #484: Pop-up messages is missing in Complete KYC
**Summary:**

When any field is empty it should show a pop-up message which is missing in Complete KYC level 3

### PR DESCRIPTION
**Pull request by shaliniv16**
Fixes #484 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by shaliniv16** [comment]
@naman14 @luckyman20 @droidchef please review.

**Comment by RajaVamsi11** [comment]
@shaliniv16 Please refer to the comment I made in #484

**Comment by RajaVamsi11** [comment]
@shaliniv16 Can you please remove the checks for KYC Registration Level 1 and level 2 as they are solved.

**Comment by luckyman20** [comment]
Closing this because of inactivity.

**Pull request closed without merging**
