### PR TITLE
Fix#1175

### LINKED ISSUE #1175: The circular mask in edit profile picture activity is not visible for dark background.
**Summary:**

The circular mask layer used as a crop layer in edit profile picture activity is not visible for dark background.

**Steps to reproduce:**

1. Go to profile fragment 
2. try to edit profile picture and choose a picture with dark background 
3. observe the circular crop.

**Expected behavior:**

the cropped section should be properly visible for every type of picture.

**Observed behavior:**

Right now that crop is not properly visible for pictures with dark background.

**Device and Android version:**

VIVO Y83, Android Version = 8.1.1

**Screenshots:**

### PR DESCRIPTION
**Pull request by EGOR-IND**
## Issue Fix
Fixes #1175 

## Screenshots
#For picture with light background

#For picture with Dark background

## Description
Made the crop more visible.

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by EGOR-IND** [comment]
Hey @devansh-299, review this one when you have time:).

**Comment by divyank00** [comment]
Is the square grid added?

**Comment by EGOR-IND** [comment]
> Is the square grid added?

Yeah actually i added the box so that people can see the constraints, square grid to position the pic and the circle is still there so they an preview the profile pic.

**Comment by divyank00** [comment]
> > Is the square grid added?
> 
> Yeah actually i added the box so that people can see the constraints, square grid to position the pic and the circle is still there so they an preview the profile pic.

can't u just give border to the circle?

**Comment by EGOR-IND** [comment]
> > > Is the square grid added?
> > 
> > 
> > Yeah actually i added the box so that people can see the constraints, square grid to position the pic and the circle is still there so they an preview the profile pic.
> 
> can't u just give border to the circle?

Yeah i can do that but i think that a grid would be better in positioning a picture because  there are different pictures in terms of size ratio, so that's why grid would be good.

**Comment by EGOR-IND** [comment]
@devansh-299 review this one.

**Review by devansh-299 — APPROVED** [review]
Looks good to me, thanks @EGOR-IND

**Pull request merged**
