### PR TITLE
redesign: add cards and card list

### LINKED ISSUE #138: Redesign: /Finance/Cards
**NOTICE** 

**Remember to checkout and send a pull request to the [redesign](https://github.com/openMF/mobile-wallet/tree/redesign)  branch.**

---

We are working on the app redesign. The prototype is done and can be found here: [show prototype](https://xd.adobe.com/view/8581e34d-8b91-49ec-7c21-000d98c8f18b-f3b0/?hints=off), and source files here: [show repository](https://github.com/letelete/mifos-pay-app-design). We will be working on the redesign implementation now.

This issue is about implementing the design and features of the CARDS tab in the Finance section.

That's what we want to achieve:

image

### PR DESCRIPTION
**Pull request by shiv07tiwari**
Fixes #138 
videotogif_2019 02 21_19 32 47
- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything
- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by shiv07tiwari** [comment]
@luckyman20 @ankurs287 Kindly review.

**Comment by shiv07tiwari** [comment]
@naman14 Kindly review this PR.

**Comment by shiv07tiwari** [comment]
@naman14 @ankurs287 Kindly review this PR

**Comment by rchtgpt** [comment]
Hey @shiv07tiwari, there has been a lot of changes in the project and thus we need a fresh start for the redesign part. 😄

**Pull request closed without merging**
