### PR TITLE
Added setError attribute to amount if ScanQrCode is pressed

### LINKED ISSUE #155: App crashes on scanning QR code if amount is empty
**Summary:**
App crashes on scanning QR code if amount field is empty.

**Steps to reproduce:**
How can we reproduce again the issue?
1) Navigate to transfer fragment and without entering amount click Scan QR code. 
2) Scan any code 
3) App crashes (BUG)

**Expected behavior:**
The user should be alerted to first enter the amount

**Device and Android version:**
OnePlus 5 
Android Oreo 8.1

### PR DESCRIPTION
**Pull request by codepoet2017390**
Fixes #155 

**SCREENSHOT**

screenshot_20181220-130643

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by luckyman20** [comment]
Good work! But we need one for VPA too. Can you please add that too as VPA can never be empty?

**Comment by codepoet2017390** [comment]
@luckyman20  Yes i already had that in consideration. The Scan QR code directly adds its results to the VPA and if u press proceed with VPA empty it alerts via Toast message

**Comment by luckyman20** [comment]
So in that case we can remove toast for VPA and add this type of error in the VPA too.

**Comment by codepoet2017390** [comment]
Should i open another issue for it?as per the guidelines

**Comment by luckyman20** [comment]
You can always edit the existing one and then do the required changes.

**Comment by codepoet2017390** [comment]
@luckyman20 these are to separate changes so do i still need to stash the commits

**Comment by codepoet2017390** [comment]
@luckyman20  Actually the App crashes because we are passing amount field to a further activity that is called on Scanning QR my main aim was to prevent crash . I will update my PR with all the errors fixed

**Comment by luckyman20** [comment]
I see that we aren't using amount which is being sent, so you can simply remove that from Intent.

**Pull request closed without merging**
