### PR TITLE
feat: #679 Added share functionality to receipt

### LINKED ISSUE #679: Feature Request: Adding option to share transaction receipt
**Summary:**

A user should be provided with the functionality to download and share the receipts of their transactions. This feature can prove useful in informing other concerned parties about the completion of a transaction .

**Steps to reproduce:**

* Go to Payments ->History tab
* Select any transaction -> View Receipt
* Here this functionality can be added

**Device and Android version:**

Xiaomi PocoF1
Android9
StockRom

### PR DESCRIPTION
**Pull request by divyank00**
## Issue Fix
Fixes #679

## Screenshots

https://user-images.githubusercontent.com/50913976/103980521-0aa5ef80-51a6-11eb-930e-8767cf2724de.mp4

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by haran2248** [comment]
Download and share have been made using the same function,if you download,it will try to share as well

**Comment by divyank00** [comment]
> Download and share have been made using the same function,if you download,it will try to share as well

Proof:

https://user-images.githubusercontent.com/50913976/103997171-c2e09180-51c0-11eb-9b8f-9ff19219ce71.mp4

**Comment by divyank00** [comment]
@devansh-299

**Comment by divyank00** [comment]
@devansh-299  Can you please review it. Thank you

**Comment by alphaNewrex** [comment]
@devansh-299 Do we need to update this PR, If Yes, I can work on it.

**Comment by devansh-299** [comment]
> @devansh-299 Do we need to update this PR, If Yes, I can work on it.

Yes, I think we can merge this after resolving the merge conflicts. Also you can work on this

**Pull request closed without merging**
