### PR TITLE
Kotlin mifospay common

### LINKED ISSUE #1295: Migration to kotlin: common package
**Summary:**
Migration to kotlin: common package

**Steps to reproduce:**
Convert java code to kotlin

### PR DESCRIPTION
**Pull request by avivijay19**
## Issue Fix
Fixes #1295 

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by devansh-299 — CHANGES_REQUESTED** [review]
@avinash14022002 your multiple pull requests regarding Java -> Kotlin migration have similar problems. You will have to fix those issues before they can be merged.

**Comment by devansh-299** [comment]
Also @avinash14022002, please get a maintainer's approval before making a pull request as in this way we can inform you if the changes suggested by you are needed now or not

**Comment by avivijay19** [comment]
> Also @avinash14022002, please get a maintainer's approval before making a pull request as in this way we can inform you if the changes suggested by you are needed now or not

Sorry @devansh-299 ,
I done according to requirement in the project description.

I had one query regarding check style workflow what is the issue for that why it failing for all the cases is there any specific guidelines for that.!

**Comment by devansh-299** [comment]
> > Also @avinash14022002, please get a maintainer's approval before making a pull request as in this way we can inform you if the changes suggested by you are needed now or not
> 
> Sorry @devansh-299 , I done according to requirement in the project description.
> 
> I had one query regarding check style workflow what is the issue for that why it failing for all the cases is there any specific guidelines for that.!

No problem! contributions are always welcome, we just don't want to make anyone's efforts go to waste.

Regarding the workflows, the build apk flow is failing for everyone and this is something we are trying to fix. For checkstyle flow, did you check the report generated?

**Comment by avinash14022002** [comment]
> > > Also @avinash14022002, please get a maintainer's approval before making a pull request as in this way we can inform you if the changes suggested by you are needed now or not
> > 
> > 
> > Sorry @devansh-299 , I done according to requirement in the project description.
> > I had one query regarding check style workflow what is the issue for that why it failing for all the cases is there any specific guidelines for that.!
> 
> No problem! contributions are always welcome, we just don't want to make anyone's efforts go to waste.
> 
> Regarding the workflows, the build apk flow is failing for everyone and this is something we are trying to fix. For checkstyle flow, did you check the report generated?

Thank you.!

Regarding the checkstyle, I refered to [Stackoverflow](https://stackoverflow.com/questions/21758533/whats-going-on-with-checkstyles-line-length-check) article but was unable to trace back.

`Error: eckstyle] [ERROR] /home/runner/work/mobile-wallet/mobile-wallet/core/src/main/java/org/mifos/mobilewallet/core/data/fineract/repository/FineractRepository.java:243: Line is longer than 100 characters (found 121). [LineLength]`

**Comment by avivijay19** [comment]
> > > > Also @avinash14022002, please get a maintainer's approval before making a pull request as in this way we can inform you if the changes suggested by you are needed now or not
> > > 
> > > 
> > > Sorry @devansh-299 , I done according to requirement in the project description.
> > > I had one query regarding check style workflow what is the issue for that why it failing for all the cases is there any specific guidelines for that.!
> > 
> > 
> > No problem! contributions are always welcome, we just don't want to make anyone's efforts go to waste.
> > Regarding the workflows, the build apk flow is failing for everyone and this is something we are trying to fix. For checkstyle flow, did you check the report generated?
> 
Thank you @devansh-299 .!

Regarding the checkstyle, I refered to [Stackoverflow](https://stackoverflow.com/questions/21758533/whats-going-on-with-checkstyles-line-length-check) article but was unable to trace back.

`Error: eckstyle] [ERROR] /home/runner/work/mobile-wallet/mobile-wallet/core/src/main/java/org/mifos/mobilewallet/core/data/fineract/repository/FineractRepository.java:243: Line is longer than 100 characters (found 121). [LineLength]`

**Comment by devansh-299** [comment]
> > > > > Also @avinash14022002, please get a maintainer's approval before making a pull request as in this way we can inform you if the changes suggested by you are needed now or not
> > > > 
> > > > 
> > > > Sorry @devansh-299 , I done according to requirement in the project description.
> > > > I had one query regarding check style workflow what is the issue for that why it failing for all the cases is there any specific guidelines for that.!
> > > 
> > > 
> > > No problem! contributions are always welcome, we just don't want to make anyone's efforts go to waste.
> > > Regarding the workflows, the build apk flow is failing for everyone and this is something we are trying to fix. For checkstyle flow, did you check the report generated?
> 
> Thank you @devansh-299 .!
> 
> Regarding the checkstyle, I refered to [Stackoverflow](https://stackoverflow.com/questions/21758533/whats-going-on-with-checkstyles-line-length-check) article but was unable to trace back.
> 
> `Error: eckstyle] [ERROR] /home/runner/work/mobile-wallet/mobile-wallet/core/src/main/java/org/mifos/mobilewallet/core/data/fineract/repository/FineractRepository.java:243: Line is longer than 100 characters (found 121). [LineLength]`

No need to refer to Stackoverflow, the error message is telling why it failed. Line number 243 in the file `FineractRepository.java`  has 121 characters when there should not be more than 100 characters in a line

**Comment by avivijay19** [comment]
> > > > > > Also @avinash14022002, please get a maintainer's approval before making a pull request as in this way we can inform you if the changes suggested by you are needed now or not
> > > > > 
> > > > > 
> > > > > Sorry @devansh-299 , I done according to requirement in the project description.
> > > > > I had one query regarding check style workflow what is the issue for that why it failing for all the cases is there any specific guidelines for that.!
> > > > 
> > > > 
> > > > No problem! contributions are always welcome, we just don't want to make anyone's efforts go to waste.
> > > > Regarding the workflows, the build apk flow is failing for everyone and this is something we are trying to fix. For checkstyle flow, did you check the report generated?
> > 
> > 
> > Thank you @devansh-299 .!
> > Regarding the checkstyle, I refered to [Stackoverflow](https://stackoverflow.com/questions/21758533/whats-going-on-with-checkstyles-line-length-check) article but was unable to trace back.
> > `Error: eckstyle] [ERROR] /home/runner/work/mobile-wallet/mobile-wallet/core/src/main/java/org/mifos/mobilewallet/core/data/fineract/repository/FineractRepository.java:243: Line is longer than 100 characters (found 121). [LineLength]`
> 
> No need to refer to Stackoverflow, the error message is telling why it failed. Line number 243 in the file `FineractRepository.java` has 121 characters when there should not be more than 100 characters in a line

@devansh-299 So,
The per line code should be less than 100 chars?
if yes i tried that but shows the same error

**Comment by devansh-299** [comment]
> > > > > > > Also @avinash14022002, please get a maintainer's approval before making a pull request as in this way we can inform you if the changes suggested by you are needed now or not
> > > > > > 
> > > > > > 
> > > > > > Sorry @devansh-299 , I done according to requirement in the project description.
> > > > > > I had one query regarding check style workflow what is the issue for that why it failing for all the cases is there any specific guidelines for that.!
> > > > > 
> > > > > 
> > > > > No problem! contributions are always welcome, we just don't want to make anyone's efforts go to waste.
> > > > > Regarding the workflows, the build apk flow is failing for everyone and this is something we are trying to fix. For checkstyle flow, did you check the report generated?
> > > 
> > > 
> > > Thank you @devansh-299 .!
> > > Regarding the checkstyle, I refered to [Stackoverflow](https://stackoverflow.com/questions/21758533/whats-going-on-with-checkstyles-line-length-check) article but was unable to trace back.
> > > `Error: eckstyle] [ERROR] /home/runner/work/mobile-wallet/mobile-wallet/core/src/main/java/org/mifos/mobilewallet/core/data/fineract/repository/FineractRepository.java:243: Line is longer than 100 characters (found 121). [LineLength]`
> > 
> > 
> > No need to refer to Stackoverflow, the error message is telling why it failed. Line number 243 in the file `FineractRepository.java` has 121 characters when there should not be more than 100 characters in a line
> 
> @devansh-299 So, The per line code should be less than 100 chars? if yes i tried that but shows the same error

Can your share the changes you made to fix this warning and the report generated afterward? I don't think this should happen

**Comment by avivijay19** [comment]
> > > > > > > > Also @avinash14022002, please get a maintainer's approval before making a pull request as in this way we can inform you if the changes suggested by you are needed now or not
> > > > > > > 
> > > > > > > 
> > > > > > > Sorry @devansh-299 , I done according to requirement in the project description.
> > > > > > > I had one query regarding check style workflow what is the issue for that why it failing for all the cases is there any specific guidelines for that.!
> > > > > > 
> > > > > > 
> > > > > > No problem! contributions are always welcome, we just don't want to make anyone's efforts go to waste.
> > > > > > Regarding the workflows, the build apk flow is failing for everyone and this is something we are trying to fix. For checkstyle flow, did you check the report generated?
> > > > 
> > > > 
> > > > Thank you @devansh-299 .!
> > > > Regarding the checkstyle, I refered to [Stackoverflow](https://stackoverflow.com/questions/21758533/whats-going-on-with-checkstyles-line-length-check) article but was unable to trace back.
> > > > `Error: eckstyle] [ERROR] /home/runner/work/mobile-wallet/mobile-wallet/core/src/main/java/org/mifos/mobilewallet/core/data/fineract/repository/FineractRepository.java:243: Line is longer than 100 characters (found 121). [LineLength]`
> > > 
> > > 
> > > No need to refer to Stackoverflow, the error message is telling why it failed. Line number 243 in the file `FineractRepository.java` has 121 characters when there should not be more than 100 characters in a line
> > 
> > 
> > @devansh-299 So, The per line code should be less than 100 chars? if yes i tried that but shows the same error
> 
> Can your share the changes you made to fix this warning and the report generated afterward? I don't think this should happen

@devansh-299,
please check #1326

**Comment by rchtgpt** [comment]
Closing this due to merge conflicts

**Pull request closed without merging**
