### PR TITLE
fix : Added missing contentDescription for ImageButtons and ImageViews

### LINKED ISSUE #401: Add missing contentDescription for ImageButtons and ImageViews
**Summary:**

The ContentDescription for ImageButtons and ImageViews is missing in the project. This is the Accessibility feature of Android. Non-textual widgets like ImageViews and ImageButtons should use the content description attribute to specify a textual description of the widget such that screen readers and other accessibility tools can adequately describe the user interface. 
My idea is to add the content description to the ImageButtons and ImageViews to fix the Android (Image without content description) **Accessibility lint warnings**.  For more info you can refer [here](https://developer.android.com/guide/topics/ui/accessibility/apps#label-elements).

### PR DESCRIPTION
**Pull request by RajaVamsi11**
Fixes #401 
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by shaliniv16** [comment]
@RajaVamsi11 please uploads screenshots.

**Comment by RajaVamsi11** [comment]
@shaliniv16 I think screenshots are not necessary as there are no UI changes. This PR resolves Android Accessbility lint warnings as explained in #401.

**Comment by RajaVamsi11** [comment]
@naman14 Can you please review this PR.

**Comment by luckyman20** [comment]
@RajaVamsi11 Please resolve the merge conflicts so that we can merge your PR.

**Comment by devansh-299** [comment]
@RajaVamsi11 closing this PR because of inactivity

**Pull request closed without merging**
