### PR TITLE
Fixes #885 - Incorporated the Mifos Pay logo in the login screen

### LINKED ISSUE #885: Feat: incorporate Mifos Pay logo in the login screen
**Summary:**
We can use the mifospay logo in LoginActivity replacing the mifos logo and the textview

### PR DESCRIPTION
**Pull request by dubeyaayush07**
Fixes #885

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by devansh-299** [comment]
@dubeyaayush07 I think the round logo would look better here.

**Comment by dubeyaayush07** [comment]
> @dubeyaayush07 I think the round logo would look better here.

As we using the rounded logo as the icon I thought of using the square one here. @luckyman20  @rachittt  What do you think?

**Rounded one**

**Comment by rachittt** [comment]
the round one looks good

**Comment by dubeyaayush07** [comment]
> the round one looks good

Changed the square logo to round.

**Comment by rachittt** [comment]
hey @dubeyaayush07, thank you for the contribution. I am not quite sure about the project maintainer but i feel like the text "Mifos pay" which is currently in the app looks more professional than the round logo. Therefore, if the maintainer agrees, we can close this PR as well as the issue.

**Pull request closed without merging**
