### PR TITLE
fix: Preserved LoginActivity on BackStack of PasscodeActivity 

### LINKED ISSUE #964: Bug: Navigating Back from PasscodeActivity Exits the App
**Summary:**
(Another BackStack Manipulation Issue)
On navigating back from the PasscodeActivity, it just exits app instead of navigating back to the 
Auth Screen. 

**Impact**  
* Consider a scenario where user by mistake enters the login flow but mind changes and instead of continuing login flow wanna register self as a customer/merchant(now there is no way achieving it directly, i.e., without restarting). In order to achieve the same now the app should be relaunched and the registration flow should be started.
* Doing all this, makes the module less user-friendly.

**Steps to reproduce:**
* Go ahead for the login flow
* When PasscodeActivity comes, navigate back
* (Now you've automatically exited)

**Expected behavior:**
User should be taken back to AuthScreen

**Observed behavior:**
Unexpected termination of app

**Device and Android version:**
Oppo A83 and 7.1.1

**Supporting Visuals:**
stack

### PR DESCRIPTION
**Pull request by s-ayush2903**
## Issue Fix
Close #964 

## Screenshots
GIF-200531_010117

## Description
Added loginActivity on Backstack

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by devansh-299** [comment]
@s-ayush2903 nice work! but can you please update the tilte and commit message to something more relevant to the changes you made like preserving `LoginActivity` in backstack while launching `PasscodeActivity` or anything similar to this

**Comment by s-ayush2903** [comment]
> @s-ayush2903 nice work! but can you please update the title and commit message to something more relevant to the changes you made like preserving `LoginActivity` in backstack while launching `PasscodeActivity` or anything similar to this

Well, it came to my mind making the commit and pr titles more semantic but i thought it is implicit as only loginActivity is the only one that constitutes to the stack, so didn't feel the need.
But anyways, i was just putting forward the reason.
So will you please tell me if rewording should be performed or leave it as it is as of now?
* PS: I have no problem in make the asked changes and ready for the same too

**Comment by Bhavnaharitsa** [comment]
@s-ayush2903 I think there is a need for change in the pr title

**Comment by devansh-299** [comment]
> > @s-ayush2903 nice work! but can you please update the title and commit message to something more relevant to the changes you made like preserving `LoginActivity` in backstack while launching `PasscodeActivity` or anything similar to this
> 
> Well, it came to my mind making the commit and pr titles more semantic but i thought it is implicit as only loginActivity is the only one that constitutes to the stack, so didn't feel the need.
> But anyways, i was just putting forward the reason.
> So will you please tell me if rewording should be performed or leave it as it is as of now?
> 
>     * PS: I have no problem in make the asked changes and ready for the same too

@s-ayush2903 I think you should change it in accordance with the changes you made so that it gets easier for everyone to keep track of the changes

**Comment by s-ayush2903** [comment]
> @s-ayush2903 I think there is a need for change in the pr title

Oh sorry ma'am, apologies

**Review by devansh-299 — APPROVED** [review]

**Review by shiv07tiwari — APPROVED** [review]
LGTM

**Comment by s-ayush2903** [comment]
@shiv07tiwari After doing some minute changes/contributions, i would like to write and contribute some real code to the project by implementing tests functionality in the app. For that I've planned to start with the core module first, and in the core module starting with testing the repository/apis with maximum possible coverage. To do so, I'll have to setUp the _testing Environment_ in the core module following the di.

Please put forward your views on the procedure and suggest changes(if applicable), after that, I'll disclose the planned sketch for the same here after making all the suggested changes

//(Spoiler Alert:- I've setUp the environ in my machine 😅)

**Pull request merged**
