### PR TITLE
fix: Added firebase:core dependency in build/gradle to avoid warnings

### LINKED ISSUE #565: Update library dependencies and build tools, configure build variant
**Summary:**

Update library dependencies and build tools versions to correct and latest ones.
Irradicate sync and build errors + warnings.
Issues with build variant.

**Steps to reproduce:**

Clone the project and build it.

**Expected behavior:**

The build should be successful without any dependency warnings or errors.

**Observed behavior:**

Dependency warnings, build tools outdated, build variant issues.

**Device and Android version:**

Android Pi.

### PR DESCRIPTION
**Pull request by Bhavnaharitsa**
Fixes #565 

Earlier the  firebase-core library was missing.
The build was showing some warnings which might sacrifice some features in the future and I guess that has caused the other mentor to raise the issue. 
 I added that in /mifospay and now the build runs clean without any warnings.

cleanbuild

- [.] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [.] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [.] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by droidchef** [comment]
@Bhavnaharitsa Thanks for the contribution.

However, before we merge this. Could you please improve the commit message by briefly describing what it does in the subject and then elaborating on why it was done, in the body of the commit message.

**Comment by Bhavnaharitsa** [comment]
> @Bhavnaharitsa Thanks for the contribution.
> However, before we merge this. Could you please improve the commit message by briefly describing what it does in the subject and then elaborating on why it was done, in the body of the commit message.

Sure will. I would like to further contribute to the project. I shall follow the contribution guidelines

**Comment by Bhavnaharitsa** [comment]
@luckyman20 @ankurs287 Could you please review this pr?

**Comment by luckyman20** [comment]
@Bhavnaharitsa Can you please change the commit title to something more sensible?

**Comment by luckyman20** [comment]
Also, direct this PR to dev branch.

**Comment by droidchef** [comment]
@Bhavnaharitsa The commit message needs to be changed. I see that you've only update the the title of the PR.

**Comment by droidchef** [comment]
The build is failing. Also now you've created multiple commits in this PR that we don't really think are necessary. Here is what I would recommend.

Close this PR.

Create a new branch from latest `dev` and then commit your changes with a fresh commit. Also add a proper commit message to it and then submit the PR.

Alternatively, you can also squash your commits here.

**Comment by Bhavnaharitsa** [comment]
@droidchef sure, will do as directed! :)

**Pull request closed without merging**
