### PR TITLE
Feat: #115 Home module refactor and redesign

### LINKED ISSUE #115: Redesign: Home
Redesign Home section (**NOTICE** Don't confuse with #114 It's completely different task)

This issue includes redesigning items visible on the screen:

* (screen 7 of 23)

All screens can be found here: [show prototype](https://xd.adobe.com/view/8581e34d-8b91-49ec-7c21-000d98c8f18b-f3b0/?hints=off)

and source files here: [show repository](https://github.com/letelete/mifos-pay-app-design)

### PR DESCRIPTION
**Pull request by letelete**
Fixes #115 

Please Add Screenshots If any UI changes.

I couldn't connect to the server. and so the error fetching balance is visible. Normally, when connected to the server user transactions history displays in the bottom sheet dialog.

ezgif-1-f49c3fc10c24

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by luckyman20** [comment]
@letelete Please squash all the commits.

**Comment by luckyman20** [comment]
Okay, then no need to squash those commits :)

**Comment by letelete** [comment]
I love how Montserrat makes the layout  dynamic and elegant as well! Roboto made the account balance look really boring.

Adding an accent color both for the balance and subtitle is too much, but personally I like the `AFTER #1` proposal on the image below. I will implement the `AFTER #2` since you've mentioned the black color for an account balance, but let me know if you wouldn't like to use the first (`AFTER #1`) proposal rather then the second one (`AFTER #2`)

image

**Comment by letelete** [comment]
Done

screenshot_1544049082

**Comment by letelete** [comment]
Done

There are still some thing which should be fixed, but I will cover that in the later commits (I'm not talking about the user interface here)

05549a67-16a1-434b-b946-c3250990ab12

**Comment by letelete** [comment]
I didn't add a currency before the transaction balance, because I've got some weird response, but it's on my todo list

This commit covers refresh layout fix. Swipe refresh was previously bugged and it got stuck by swiftly moving between fragments while active.

**Comment by luckyman20** [comment]
I liked the `AFTER #1` please implement that.

**Comment by letelete** [comment]
I've changed colors to match the `AFTER #1` proposal

**Comment by letelete** [comment]
I've changed colors to match the `AFTER #1` proposal 

screenshot_20181206-133704

**Pull request merged**
