### PR TITLE
README.md changes from gradlew to ./gradlew

### LINKED ISSUE #910: Typo: Travis CI commands in README.md
**Summary:**

Travis CI commands in the [README.md](https://github.com/openMF/mobile-wallet#travis-ci) file are not entirely correct.

**Expected behavior:**

the commands should be correct according to each Operating System.

### PR DESCRIPTION
**Pull request by haran2248**
## Issue Fix
Fixes #910 

## Description

Git Travis CLI changed from ./gradlew to gradlew

##

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by rchtgpt** [comment]
hi @haran2248, as far as I know, the windows commands are correct. you just need to write a new paragraph which says:

> If you are using Git Bash, you can use the following commands:
`./gradlew check` quality checks on your project’s code using Checkstyle and generates reports from these checks.
`./gradlew spotlessApply` checks and applies formatting to any plain-text file.
`./gradlew build` provides a command line to execute build script. 

@devansh-299 @Bhavnaharitsa do you guys agree?

**Comment by devansh-299** [comment]
> 
> 
> hi @haran2248, as far as I know, the windows commands are correct. you just need to write a new paragraph which says:
> 
> > If you are using Git Bash, you can use the following commands:
> > `./gradlew check` quality checks on your project’s code using Checkstyle and generates reports from these checks.
> > `./gradlew spotlessApply` checks and applies formatting to any plain-text file.
> > `./gradlew build` provides a command line to execute build script.
> 
> @devansh-299 @Bhavnaharitsa do you guys agree?

@dotrachit  Yes, I just confirmed. Windows commands are right and for git bash, we do need  to add the paragraph you mentioned

**Comment by haran2248** [comment]
@devansh-299 @dotrachit Ok i will work on the necessary changes

**Comment by haran2248** [comment]
Pls let me know if the changes that i have made is correct:)

**Pull request closed without merging**
