### PR TITLE
 Created Issue Template

### PR DESCRIPTION
**Pull request by luckyman000786**

### CODE REVIEW

**Comment by therajanmaurya** [comment]
@luckyman000786 Please follow all the instructions that I told in the previous PR and Please add `.github` folder in the root of the project and add PULL request, CONTRIBUTIONS, ISSUE template into it.

**Comment by luckyman000786** [comment]
@therajanmaurya Now Review It !

**Comment by therajanmaurya** [comment]
Looks good, Remove the `PULL_REQUEST_TEMPLATE.md` from the root of the project and everything looks fine.

**Comment by luckyman000786** [comment]
@therajanmaurya `PULL_REQUEST_TEMPLATE.md` is in .github folder only not in the root of the project

**Pull request closed without merging**
