### PR TITLE
Remove All hardcoded strings

### LINKED ISSUE #1090: Remove all "Hardcoded Strings" in all XML file of this app.
**Summary:**

Remove all "Hardcoded string" by creating the strings in "strings.xml" file.

**Steps to reproduce:**

Hardcoded strings are present in "item_si.xml" and many more XML files. Simply open the file and wait for the loading of XML. You will find that there are many hardcoded strings.

**Expected behavior:**

The app should not show the "Hardcoded string" warning.

**Observed behavior:**

Warning Screenshot in "item_si" XML file:
Capture

### PR DESCRIPTION
**Pull request by deepak-prajapatii**
## Issue Fix
Fixes #1090 

## Description
Remove all Hardcoded Strings and warnings as much as possible.

## 
- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by deepak-prajapatii** [comment]
@Nayan @siebrand @vorburger @vishwasbabu @EGOR-IND Please review my PR ASAP.

**Comment by vorburger** [comment]
@deepak-prajapatii As per comments on PRs, I'm not maintaining this project, and cannot help review PRs in this repo. Please stop "tagging" me.

It looks like @devansh-299 is an active committer in this project. I'm sure he will review and get back to you when he can.

If there's not enough active committers on this project, then the "right" thing to do in open source could be for the existing committers to invite new people who recently contributed quality to become additional committers... would this potentially interest you? You could write to the mifos-developer@lists.sourceforge.net mailing list to discuss that, if taking on this responsability interests you.

**Comment by deepak-prajapatii** [comment]
> @deepak-prajapatii As per comments on PRs, I'm not maintaining this project, and cannot help review PRs in this repo. Please stop "tagging" me.
> 
> It looks like @devansh-299 is an active committer in this project. I'm sure he will review and get back to you when he can.
> 
> If there's not enough active committers on this project, then the "right" thing to do in open source could be for the existing committers to invite new people who recently contributed quality to become additional committers... would this potentially interest you? You could write to the mifos-developer@lists.sourceforge.net mailing list to discuss that, if taking on this responsability interests you.

Sure

**Comment by deepak-prajapatii** [comment]
@devansh-299 Please review my PR.

**Comment by siebrand** [comment]
Please do not tag me. I do not do any code review on this project. I only have access because of my involvement in L10n.

**Comment by deepak-prajapatii** [comment]
> Please do not tag me. I do not do any code review on this project. I only have access because of my involvement in L10n.

Okay, Next time I don't do

**Comment by deepak-prajapatii** [comment]
@devansh-299 Please review my PR.

**Comment by deepak-prajapatii** [comment]
@devansh-299 please review my PR,

**Comment by devansh-299** [comment]
@deepak-prajapatii thank you for your contribution, this is a pretty big pull request and I shall review it as soon as possible and get back to you!

**Review by Supriyo9 — APPROVED** [review]

**Comment by Prashant830** [comment]
@deepak-prajapatii  I think, In your branch have a code conflict . Are u still able to resolved it??

**Pull request closed without merging**
