### PR TITLE
feat: improved the PR template

### PR DESCRIPTION
**Pull request by laxyapahuja**
## Description
Improved the existing Pull Request Template.

## Screenshots
Making a PR
image

Preview
image

### CODE REVIEW

**Comment by laxyapahuja** [comment]
@luckyman20 can you please review this PR? thanks. :D

**Comment by luckyman20** [comment]
@laxyapahuja Please attach a screenshot of how it would look like, same applies for your issue template PR.

**Comment by laxyapahuja** [comment]
@luckyman20 
image

**Comment by luckyman20** [comment]
@laxyapahuja Push the changes to `dev` branch.

**Pull request closed without merging**
