### PR TITLE
Use TextInputLayout instead of EditText in MobileVerification Activity

### PR DESCRIPTION
**Pull request by haran2248**
## Issue Fix
Fixes #{Issue Number}
#825 

## Screenshots
WhatsApp_Image_2020-07-23_at_14 02 43 1

## Description

WhatsApp_Image_2020-07-23_at_14 02 43_(1) 1
WhatsApp_Image_2020-07-23_at_14 02 43_(2) 1
WhatsApp_Image_2020-07-23_at_14 02 44 1

Description

The EditTexts in activity_mobile_verification has been changed to TexpInputLayouts and TextInputEditTexts for better user experience and understanding.

type:feat,The Phone no and otp editexts have been changed to InputLayouts and InputEditTexts.But the id of each has not been changed so that it functions properly

##

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by s-ayush2903** [comment]
Please follow the templates, learn about branching strategies and squash your commits to single one. 
For more info, you may have a look at [contribution guidelines](https://github.com/openMF/mobile-wallet#how-to-contribute)

**Comment by haran2248** [comment]
I have squashed my two PRs to a single commit.To which branch should i make the PR?The dev branch or the redesign branch?Since the changes are only in XML?

**Comment by sashank27** [comment]
@haran2248 since this issue is closed, I would request to close this PR as it is not relevant

**Comment by devansh-299** [comment]
@haran2248 #1016 also solves the similar issue. Please close anyone pull request

**Pull request closed without merging**
