### PR TITLE
fix: #791 Added scrollers to history fragment

### LINKED ISSUE #791: feat:  Scroll to Bottom in History Fragment
**Description**

If there is a large amount of transaction history available the user wants to look for a previous transaction then he needs to scroll a lot of times, what if there is an option or icon for the same this would be very useful in our app.

### PR DESCRIPTION
**Pull request by divyank00**
## Issue Fix
Fixes #791 & #812

## Screenshots

https://user-images.githubusercontent.com/50913976/104511131-490e3500-5612-11eb-867d-a7ad3f20fdc1.mp4

## Description
Added a scroller in history fragment to scroll up and down

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by EGOR-IND — APPROVED** [review]
you could make a single button for this so that it takes less space, but all things aside it seems fine to me.

**Comment by divyank00** [comment]
@devansh-299 @s-ayush2903  Please Review

**Comment by devansh-299** [comment]
> 
> 
> you could make a single button for this so that it takes less space, but all things aside it seems fine to me.

Yes, a single button would be a better choice. In fact, we can have a rotating animation of the arrow transitioning from up pointing to down pointing and vice versa

**Comment by divyank00** [comment]
> > 
> > 
> > you could make a single button for this so that it takes less space, but all things aside it seems fine to me.
> 
> Yes, a single button would be a better choice. In fact, we can have a rotating animation of the arrow transitioning from up pointing to down pointing and vice versa 

But if user is in middle, how can he have to options: Scroll Up and Scroll Down?

**Comment by devansh-299** [comment]
> 
> 
> > > you could make a single button for this so that it takes less space, but all things aside it seems fine to me.
> > 
> > 
> > Yes, a single button would be a better choice. In fact, we can have a rotating animation of the arrow transitioning from up pointing to down pointing and vice versa
> 
> But if user is in middle, how can he have to options: Scroll Up and Scroll Down?


You can have a threshold(let's say after half of the items) after which the transition occurs so that even in the middle or nearby user can have a choice to either move to top or bottom

**Comment by divyank00** [comment]
@devansh-299 Can you the updated code, please. Do you think this is fine now?

**Comment by divyank00** [comment]
I have made a new pr #1155, that fixes this, so closing this

**Pull request closed without merging**
