### PR TITLE
Update Readme

### LINKED ISSUE #878: Update Readme
**Summary:**

Since the Official logo of mifos pay is now out so replacing the old mifos logo with the new mifos pay one.

### PR DESCRIPTION
**Pull request by refactor-droidyy**
## Issue Fix
Fixes #878 

## Screenshots

Refer to this link https://github.com/refactor-droidyy/mobile-wallet/tree/updateRedame

## Description
Update Readme 

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by rachittt** [comment]
@refactor-droidyy hey, kindly attach a screenshot of the change you've made.

**Comment by rachittt** [comment]
Also change the commit title to something more specific.

**Comment by Bhavnaharitsa** [comment]
@refactor-droidyy Are you sure that's the final mifos icon?

**Comment by rachittt** [comment]
@Bhavnaharitsa hey, this logo is for **Mifos Pay i.e. Mobile Walle appt** and **not Mifos** itself. As of what I have been told by the project maintainer, it has been approved by the CEO of Mifos. So adding it in the project README makes complete sense.

**Comment by rachittt** [comment]
Also @refactor-droidyy, i feel like the[ square logo](https://drive.google.com/drive/u/3/folders/10NTOigKiTYPH0ONbIvdGvVZHrnosQNyy) would look better here instead of the round logo.

**Comment by refactor-droidyy** [comment]
@rachittt sure I will replace it.

**Comment by refactor-droidyy** [comment]
@rachittt I guess the rounded one looks good. what's your opinion?

ada

Screenshot from 2020-04-10 11-02-30

**Comment by rachittt** [comment]
the square one looks pretty cool, to be honest. @luckyman20 views?

**Comment by rachittt** [comment]
also, don't forget to squash your commits.

**Comment by refactor-droidyy** [comment]
newone

**Comment by rachittt** [comment]
@refactor-droidyy please remove the unnecessary file additions from the PR so that it can be merged.

**Comment by Bhavnaharitsa** [comment]
@devansh-299  Yes we can close it :).

**Pull request closed without merging**
