### PR TITLE
fix:An incorrect pop-up message appears when clicked on ADD button in  Saved Cards

### LINKED ISSUE #431: An incorrect pop-up message appears when clicked on ADD button in Saved Cards.
**Summary:**

An incorrect pop-up message appears when clicked on ADD button in Saved Cards.

**Device and Android version:**

Device Real Me 2
Android Version 8.1.0

**Gif:**

videotogif_2019 03 08_16 24 50

### PR DESCRIPTION
**Pull request by shaliniv16**
Fixes #431 

**Gif:**

videotogif_2019 03 08_17 23 57

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by shaliniv16** [comment]
@naman14 @droidchef @luckyman20 please review.

**Review by shiv07tiwari — CHANGES_REQUESTED** [review]
@shaliniv16 Maybe you can add both in if-else if cases. That will be a better implementation.

**Comment by luckyman20** [comment]
@shaliniv16 Why do you want to show a single Toast message when there is separate error for each text view already?

**Comment by luckyman20** [comment]
Closing this because of inactivity.

**Pull request closed without merging**
