### PR TITLE
Fixed Build failure

### LINKED ISSUE #244: Failed to resolve Google play services auth.
**Summary:**
Cannot resolve google play services auth.

**Steps to reproduce:**
Build the app,

**Expected behavior:**
Build correct.

What did you expect the app to do?

**Observed behavior:**

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**
screenshot 116
screenshot 117

I would like to work on the issue.

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #244 #243 #246 #161 

Please Add Screenshots If any UI changes.
screenshot 118
screenshot_20190125-150735

Please Add Summary of what changes you have made.(Optional)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by jddeep** [comment]
@luckyman20 @ankurs287 kindly review and merge the PR. thank you.

**Comment by jddeep** [comment]
@luckyman20 @ankurs287 kindly review and merge the PR. Thank you.

**Comment by luckyman20** [comment]
@jddeep Closing this PR because you didn't first got assigned this issue. Moreover, the project is working fine for me. So first please discuss it with the community and get it assigned and then open a PR.

**Comment by jddeep** [comment]
@luckyman20 By the community do you mean the gitter channel? And there is a app crash at the start ass mentioned in #245 . And the errors of #244 and #243 are there as you can see in the screenshots there. Kindly look into it and reply. Thanks.

**Comment by luckyman20** [comment]
By community discussion I mean the discussion on the issue only.

**Comment by jddeep** [comment]
@luckyman20 Okay cool. And btw I also messaged about the problems on the gitter channel with you tagged. You can check into that. Thanks.

**Pull request closed without merging**
