### PR TITLE
Implemented Email Address validator.

### LINKED ISSUE #252: No Email validator present in the Sign Up Details page.
**Summary:**There is no validation check for correct email while filling up details.

**Steps to reproduce:**
Go to Sign up.
Proceed.
enter details.

**Expected behavior:**
To have a validation check on  the email,

**Observed behavior:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #252 

Please Add Summary of what changes you have made.(Optional)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by luckyman20** [comment]
Run `gradlew build` on your local machine and you will know the reason.

**Comment by RajaVamsi11** [comment]
@jddeep Have you run the unit tests with `./gradlew check` locally to make sure you didn't break anything.
If tests had passed then there must be no error in passing Travis

**Comment by jddeep** [comment]
> Run `gradlew build` on your local machine and you will know the reason.

@luckyman20 Well the app built successfully in Android Studio and ran perfectly on my device.

**Comment by luckyman20** [comment]
I am not talking about the Android build, you have to run the given command into the terminal and then you will see the errors.

**Comment by jddeep** [comment]
@luckyman20 @RajaVamsi11 Okay I ran the commands in the terminal. 
``` Execution failed for task ':mifospay:checkstyle'.
> Checkstyle rule violations were found. See the report at: file:///C:/Users/jaideep%20pc/AndroidStudioProjects/mobile-wallet/mifospay/build/reports/checkstyle/checkstyle.html ```
This is the error I got. Can you please help me out here.

**Comment by jddeep** [comment]
@luckyman20 I never faced such an issue before while open source contributing. It will be great if I get to know the reason behind this and a possible solution for this error.

**Comment by jddeep** [comment]
@luckyman20 Yeah I resolved the error. Now you can review it. Thanks.

**Comment by ankurs287** [comment]
@jddeep @luckyman20 refer to my comment on the issue.

**Pull request closed without merging**
