### PR TITLE
feat: Changing the default android icon to the official Mifos logo. 

### PR DESCRIPTION
**Pull request by njwardhan**
**Summary-**

This pull request (In accordance with issue #521)  will give a better look to the app when it is cloned. 

**A link to demonstrate the changes made in the app (Contains screenshots of the UI)-**

https://docs.google.com/document/d/1a-2bq4vu56zR85zm2ArgRk7HSTTpegKk-FZXIoeoDvI/edit?usp=sharing

### CODE REVIEW

**Comment by njwardhan** [comment]
Respected Sir @droidchef,

I have submitted this PR and it is having some issues in its build. I would request you to guide me through this failed check.

Thank you.

**Comment by shaliniv16** [comment]
@njwardhan Can you please open an issue regarding this PR?

**Comment by njwardhan** [comment]
@shaliniv16 , sure, I will.

**Comment by njwardhan** [comment]
I have created an issue, #521  regarding this Pull Request.

**Pull request closed without merging**
