### PR TITLE
fix:App crash while searching in trusted merchant fragmet

### LINKED ISSUE #195: App crashes while searching in Trusted Merchants Fragment if the device is not connected to the internet
**Summary:**

App crashes while searching in Trusted Merchants Fragment if the device is not connected to the internet

**Steps to reproduce:**

1. Disconnect your device from the internet
2. Click Trusted Merchants option in Home activity
3. Type what you want to search for in the search box
4. APP CRASHES(BUG)

**Expected behavior:**

App should display a popup message instead of crashing.

**Device and Android version:**

Realme 2 Pro
Android version 8.1.0

### PR DESCRIPTION
**Pull request by shaliniv16**
Fixes #195

### CODE REVIEW

**Comment by shaliniv16** [comment]
@Nayan please review

**Comment by shaliniv16** [comment]
@luckyman20 please review.

**Comment by ankurs287** [comment]
@shaliniv16 good job but you could have also put a placeholder 'No Merchants Found' when search results is null.

**Comment by shaliniv16** [comment]
@ankurs287 okay sure.

**Pull request merged**
