### PR TITLE
Migrate SIFragment to Jetpack compose

### LINKED ISSUE #1569: Migrate xml to Jetpack compose - standinginstruction/ui/SIFragment
**Summary:**

Migrate xml to Jetpack compose - standinginstruction/ui/SIFragment

**Steps to reproduce:**

How can we reproduce again the issue?

**Expected behavior:**

What did you expect the app to do?

**Observed behavior:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

### PR DESCRIPTION
**Pull request by AdityaKumdale**
## Issue Fix
Fixes #1569

## Screenshots
image

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by PratyushSingh07** [comment]
Hi @AdityaKumdale , I am already working on the entire payments fragment which you can see in #1548 . I know that PR has been dormant for some time but I will now be continuing with it. I just have to migrate HistoryScreen to compose and then my PR will be complete

**Comment by AdityaKumdale** [comment]
@PratyushSingh07 Cool, I will work on different features then, is my pr helpful though? I will take on fragments outside payment screen then.

**Comment by PratyushSingh07** [comment]
I would suggest getting rid of compose view that you have used in XML and binding from the fragments

**Comment by PratyushSingh07** [comment]
closing this as duplicate of #1548

**Pull request closed without merging**
