### PR TITLE
No trusted merchants found message added

### LINKED ISSUE #371: Trusted merchants
Summary
When searching for trusted merchants on finding no merchants to display no error message is displayed

Expected behavior
Error message should be displaced

### PR DESCRIPTION
**Pull request by manddy**
Fixes
#371 

Summary
After searching for trusted merchants if no keywords matches  then error text message displayed of no trusted merchants found

Please make sure these boxes are checked before submitting your pull request 

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by manddy** [comment]
@naman14 @ankurs287 @luckyman20  kindly review my pull request

**Comment by RahulPrajapati97** [comment]
@RajaVamsi11  Is this necessary to search all data of merchant means why we are not searching merchant by their name?

**Comment by RajaVamsi11** [comment]
@RahulPrajapati97 Can you please elaborate your query. You can discuss the details of project in gitter channel https://gitter.im/openMF/mobile-wallet. Discussing in Github comments is quite odd. Join gitter and ask your queries there:smiley: .

**Comment by rachittt** [comment]
Closing this because of inactivity.

**Pull request closed without merging**
