### PR TITLE
fix: Unescaped apostrophe in string

### PR DESCRIPTION
**Pull request by arboledasaa**

### CODE REVIEW

**Comment by luckyman20** [comment]
@arboledasaa Change commit to `fix: Unescaped apostrophe in string`

**Comment by arboledasaa** [comment]
> @arboledasaa Change commit to `fix: Unescaped apostrophe in string`

@luckyman20 done

**Comment by arboledasaa** [comment]
Help?

**Comment by arboledasaa** [comment]
Help?

@luckyman20 Do you have write access? Do you know someone and could you please put the good word?

**Pull request merged**
