### PR TITLE
chore: converted strings displayed to the user into string resource objects.

### LINKED ISSUE #1054: Every user displayed message/text should be a string resource object
**Summary:**

 We should make a string resource object for every user displayed message/text, so that if in the future we plan to add multi-language functionality, then we can easily provide a multi-language alternative.

For eg:- we have many variables declared inside `Constants.java` which contain user displayed message/text and could be a hindrance in the future while adding multi-language functionality.

### PR DESCRIPTION
**Pull request by ReCodee**
Fixes #1054 

## Description
Converted strings displayed to the user into string resource objects and strings which are being used in the backend are in `Constants.java`

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by ReCodee** [comment]
@shiv07tiwari @devansh-299  Please review this PR :)

**Review by devansh-299 — APPROVED** [review]
Looks good to me!

**Comment by Prashant830** [comment]
@ReCodee I think, In your branch have a code conflict . Are u still able to resolved it??

**Comment by therajanmaurya** [comment]
Unrelated and not needed anymore

**Pull request closed without merging**
