### PR TITLE
fix: error message for finding invalid or wrong mobile number

### LINKED ISSUE #607: bug: Wrong error message while sending money using Mobile Number
**Summary:**
If you try to transfer money using Mobile Number, a Snackbar appears with a wrong error message.

**Steps to reproduce:**
Payments -> Send -> Mobile Number -> Add an amount -> Type the mobile number -> Submit

**Expected behavior:**

An error message saying "Error finding Mobile Number" should be displayed.

**Observed behavior:**

An error message saying "Error finding Virtual Payment Address" is displayed.

**Device and Android version:**
Mi A2
Android 9 Pie

**Screenshots:**
WhatsApp Image 2019-12-16 at 21 30 16

### PR DESCRIPTION
**Pull request by PiyushSharma99**
Fixes #607

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by PiyushSharma99** [comment]
@jddeep @luckyman20 @shiv07tiwari Please review. Thanks!

**Comment by laxyapahuja** [comment]
I think it'll be better if you attach a screenshot of the snack bar :)

**Comment by PiyushSharma99** [comment]
Done @laxyapahuja :)

**Comment by PiyushSharma99** [comment]
@luckyman20 What is build error here about `pmd`. I am quite unable to understand as I could not find the mentioned pmd.html file locally.

**Comment by laxyapahuja** [comment]
@PiyushSharma99 you'll have to run a local Gradle build check for that. Check [this](https://gist.github.com/laxyapahuja/e30921a9478bdf3a9e166a023ce1882c) out on how to do the same.

**Comment by PiyushSharma99** [comment]
error2

**Comment by PiyushSharma99** [comment]
@laxyapahuja This is what I could find. Nothing as such that I could do to fix this. :/

**Comment by laxyapahuja** [comment]
> @laxyapahuja This is what I could find. Nothing as such that I could do to fix this. :/

Your code has some PMD violations. You can find them going to build/pmd/pmd.html

**Comment by jddeep** [comment]
@PiyushSharma99 please check if you have a pmd folder inside your build folder of the application/project.

**Comment by jddeep** [comment]
@PiyushSharma99 please check if you have a pmd folder inside your build folder of the application/project.

**Comment by PiyushSharma99** [comment]
Thanks @jddeep . I generated the report and found it inside the folder. Updated the code :)

**Comment by PiyushSharma99** [comment]
> I think you can check from the view pager about which fragment we are exactly on.

@luckyman20 I could not find any ViewPager object/instance in the `SendFragment`? But here we can just simply determine whether it is mobile or vpa and show the msg accordingly. Do let me know your thoughts :)

**Comment by luckyman20** [comment]
Sorry, I meant chip. You can get that info directly from chips.

**Comment by rachittt** [comment]
@PiyushSharma99 what is the status?

**Comment by luckyman20** [comment]
Closing this because of inactivity.

**Pull request closed without merging**
