### PR TITLE
Edit Text Cleared on getting focused

### LINKED ISSUE #290: Redesign: EditText hint should get cleared when clicked in Edit Profile
**Summary:**

EditText hint should get cleared when the textBox is clicked in Edit Profile.

**Steps to reproduce:**

1. Open app in redesign and go to Edit Profile
2. Click on any Edit Text textbox.
3. Text hint should be automatically cleared.

**Device and Android version:**

OnePlus5 Android 9(Pie)

### PR DESCRIPTION
**Pull request by codepoet2017390**
Fixes #290 

**Please Add Screenshots If any UI changes.**

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by RajaVamsi11** [comment]
@codepoet2017390 Please fix the build.

**Comment by RajaVamsi11** [comment]
@codepoet2017390 Squash your commits.

**Comment by letelete** [comment]
Inputs shouldn't be cleared. Read my reply here for more details: https://github.com/openMF/mobile-wallet/issues/290#issuecomment-464435540

**Comment by naman14** [comment]
Agreed with @letelete Closing this

**Pull request closed without merging**
