### PR TITLE
Created Pull Request Template

### PR DESCRIPTION
**Pull request by luckyman000786**

### CODE REVIEW

**Comment by therajanmaurya** [comment]
@luckyman000786 Please send the PULL request template as we are using in self-service. we need all type of checks here too to maintain the project quality.

**Comment by luckyman000786** [comment]
@therajanmaurya I have updated the Pull Request Template according to self-service app. Please review the same.

**Comment by therajanmaurya** [comment]
Looks good, Please quash your commit and follow [commit guidelines](https://github.com/openMF/mobile-wallet/wiki/Commit-style-guide). 
Your commit message will be like this 
`chore: Add PULL REQUEST template`

**Comment by luckyman000786** [comment]
@therajanmaurya I have squashed the commits and renamed the commit message

**Comment by therajanmaurya** [comment]
Good, can you please remove the string `Updated Pull Request Template` from commit message.
you can edit commit message using `git commit --amend` and force push again.

**Comment by luckyman000786** [comment]
@therajanmaurya Now check .

**Comment by therajanmaurya** [comment]
Nice !!

**Pull request merged**
