### PR TITLE
 added function when one faq opens the other closes and also added sc…

### LINKED ISSUE #654: fix: one faq doesnt close when other is open and there is no scroll bar too
**Summary:**

When one FAQ opens, the other should close and scroll bar should be in FAQ fragment in case many FAQs are added

**Device and Android version:**
Any

### PR DESCRIPTION
**Pull request by Bhavnaharitsa**
Fixes #654 
Added function when one faq opens the other closes and added scroll view too

- [.] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [.] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [.] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Bhavnaharitsa** [comment]
@luckyman20 please review

**Comment by shiv07tiwari** [comment]
@Bhavnaharitsa Please attach a screenshot/recording of the changes.

**Comment by Bhavnaharitsa** [comment]
@shiv07tiwari Yes sir, shortly

**Comment by Bhavnaharitsa** [comment]
ezgif com-video-to-gif

@shiv07tiwari Sir, I have added dummy FAQs just to show you the working of Scroll view. 
I have not committed it and reset it in my branch

**Comment by shiv07tiwari** [comment]
@Bhavnaharitsa Why do we need other answers to collapse if a user clicks on one of the questions? There may be scenarios where multiple answers are related to each other.

**Comment by Bhavnaharitsa** [comment]
The do you just want me to add the scroll bar? As you said, there are possibilities of that occurrence so let me just add the scroll bar and leave the function part?

**Comment by shiv07tiwari** [comment]
Yes I guess it's not important to close other answers.

**Comment by Bhavnaharitsa** [comment]
Then this issue has lost its life. But I guess we need a scroll bar in case further faqs are added.
Should I open that as an issue?

**Comment by shiv07tiwari** [comment]
That's why I asked why do you think it is important to collapse other answers.

**Comment by Bhavnaharitsa** [comment]
This feature I had observed in other apps where one faq closes when other is opened. That's the reason i opened here because the faqs were abruptly hanging even when the user didnt need and user has to close everytime manually which I felt was cumbersome. When I saw this, I realised sole other has already opened and it's long unseen so I took this up.

**Comment by Bhavnaharitsa** [comment]
@shiv07tiwariPlease throw some light on this issue and let's make things clear if we need this particular function or let's just stick to adding scroll view

**Comment by Bhavnaharitsa** [comment]
@naman14 What is your thoughts on this issue?

**Comment by naman14** [comment]
@Bhavnaharitsa only scrollview is fine. No need to collapse other faqs when expanding onother one.

**Comment by Bhavnaharitsa** [comment]
Thanks, it was a long pending discussion.

**Pull request closed without merging**
