### PR TITLE
Receipt sharing feature added to payment fragment

### LINKED ISSUE #679: Feature Request: Adding option to share transaction receipt
**Summary:**

A user should be provided with the functionality to download and share the receipts of their transactions. This feature can prove useful in informing other concerned parties about the completion of a transaction .

**Steps to reproduce:**

* Go to Payments ->History tab
* Select any transaction -> View Receipt
* Here this functionality can be added

**Device and Android version:**

Xiaomi PocoF1
Android9
StockRom

### PR DESCRIPTION
**Pull request by haran2248**
## Issue Fix
Fixes #679 

https://user-images.githubusercontent.com/56928954/103966694-62ccf980-5186-11eb-8ca9-4175e7856b4c.mp4

## Description

Share receipt feature has been added which helps share the link of the receipt.

##

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by haran2248** [comment]
The third commit is actually the squashed one of the first two commits I dont understand why it is not getting squashed properly.
Im working on it

**Comment by divyank00** [comment]
I guess sharing meant by sharing the file, not the link. Still, just confirm with @luckyman20.

Follow the commit guideline rules given in the wiki section

**Comment by haran2248** [comment]
> I guess sharing meant by sharing the file, not the link. Still, just confirm with @luckyman20.
> 
> Follow the commit guideline rules given in the wiki section

In order to share the file you have to download first in this codebase,thats why its better to share the link

**Comment by divyank00** [comment]
> > I guess sharing meant by sharing the file, not the link. Still, just confirm with @luckyman20.
> > Follow the commit guideline rules given in the wiki section
> 
> In order to share the file you have to download first in this codebase,thats why its better to share the link

Then let me try sharing the file along with the link because I feel that would be better.

Let @luckyman20 decide.

**Comment by divyank00** [comment]
Check #1142 , doesn't that seem better?

**Comment by haran2248** [comment]
> Check #1142 , doesn't that seem better?

But i dont see why you have to download the file to share it

**Comment by haran2248** [comment]
I feel it is the same thing

**Comment by divyank00** [comment]
Do you feel #1142 and #1144 together can be much better than the current UI?

**Comment by haran2248** [comment]
I accidentally mixed two issues together.I am closing this PR

**Comment by divyank00** [comment]
Video doesn't match with the code

**Pull request closed without merging**
