### PR TITLE
Update SDK versions

### LINKED ISSUE #217: Increase the compile and target SDK version
**Summary:**
The compileSdkVersion and targetSdkVersion which are set to versions 26 and 26, respectively, must be changed to 28( Android Pie)  as the latest Android APIs must be used to make use of the latest features. 

@luckyman20 @ankurs287 Can you please review this issue? I will fix this.

### PR DESCRIPTION
**Pull request by RajaVamsi11**
Fixes #217 
Updated the compile and target SDK versions of the app

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by RajaVamsi11** [comment]
@luckyman20 Please review this PR?

**Comment by codepoet2017390** [comment]
@RajaVamsi11 all work you do is to be pushed to dev branch. master contains to the stable working code

**Comment by RajaVamsi11** [comment]
@codepoet2017390 When I am changing the base branch to dev, other commits which are not mine is showing up. Do you know how to solve this problem?

**Comment by codepoet2017390** [comment]
@RajaVamsi11  make sure your forked repo and your local dev branches are even with the upstream dev

**Comment by RajaVamsi11** [comment]
Closed from my side due to some complexity in branch rebase. I am sorry for this kind of mistakes.

**Pull request closed without merging**
