### PR TITLE
feat : Added share functionality

### PR DESCRIPTION
**Pull request by Vipinsoni38**
Fixes #{#439}

Added a small share Image Button which helps the user to share his QR code with others

Please Add Screenshots If any UI changes.
Screenshot_20190309-125802
Screenshot_20190309-124737

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Vipinsoni38** [comment]
Yup Just did that!

**Comment by RajaVamsi11** [comment]
@Vipinsoni38 Run this **./gradlew check** locally and you will know where is Travis is failing.

**Comment by luckyman20** [comment]
@Vipinsoni38 Please resolve the merge conflicts!

**Comment by rachittt** [comment]
fixed in #810.

**Pull request closed without merging**
