### PR TITLE
Fix: Removed unnecessary toast in FAQs section

### LINKED ISSUE #586: Bug:  Unnecessary Toast In FAQ Section
**Summary:**
On clicking the list items of the FAQ section, a toast message is being displayed.

**Steps to reproduce:**
FAQ -> Click on any Question

**Expected behavior:**
No toast should be shown as it does not look good from the eyes of the user.

**Observed behavior:**
A toast is displayed with some irrelevant text in it.

**Device and Android version:**
Android 9, Mi A2
**Screenshots:**
issue

### PR DESCRIPTION
**Pull request by rachittt**
Fixes #586 

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by rachittt** [comment]
@luckyman20 can you check this?

**Comment by luckyman20** [comment]
@rachittt Travis CI Build is failing.

**Comment by shiv07tiwari** [comment]
@rachittt Any updates?

**Comment by rachittt** [comment]
@shiv07tiwari making a new PR for the same.

**Pull request closed without merging**
