### PR TITLE
Fixes #870 - Incorporated the official Mifos Pay logo into the app

### LINKED ISSUE #870: Incorporate the official Mifos Pay logo into the app
**Summary:**

The official [logo](https://drive.google.com/drive/folders/1-TJ-pB3h6CvKWcR0LBcKbrypWpDnNKdo) for Mifos Pay has been designed and approved. We should start implementing this logo in the app.

### PR DESCRIPTION
**Pull request by dubeyaayush07**
Fixes #870
**Updated**

 

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by dubeyaayush07** [comment]
@rachittt What do you think?

**Comment by dubeyaayush07** [comment]
@luckyman20 This is the way Android recommends for supporting different density screens as I generated these folders using the Image Asset wizard for adaptive icons.

**Comment by rachittt** [comment]
@dubeyaayush07 wait for some time, there might be a change in the shade of the logo. we will inform you asap.

**Comment by rachittt** [comment]
@dubeyaayush07 hey! extremely sorry for the delayed response. you can find the final logo for Mobile Wallet [here](https://drive.google.com/open?id=10NTOigKiTYPH0ONbIvdGvVZHrnosQNyy)

**Comment by dubeyaayush07** [comment]
@rachittt  **Updated**

**Comment by dubeyaayush07** [comment]
> I don't think it is necessary to put the logo in every mipmap folder.

@luckyman20 Android Image Asset Studio generated these files automatically to support different screen densities for adaptive icons.

**Pull request merged**
