### PR TITLE
Fixes not hidden issue template hints

### PR DESCRIPTION
**Pull request by OussEmaDevCode**
Please Add Summary of what changes you have made.(Optional)

Improved the issue template so that is hides the hints in each section.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by luckyman20** [comment]
@OussEmaDevCode Can you please upload a screenshot of how the issue template will look like after these changes?

**Comment by OussEmaDevCode** [comment]
@luckyman20 Here you go:
Capture d’écran (187)

**Comment by luckyman20** [comment]
@OussEmaDevCode In that case, we want to show these hints otherwise it wouldn't make any sense. If you think it is relevant, then please tell otherwise close this PR. Thank you for your contributions :)

**Comment by OussEmaDevCode** [comment]
@luckyman20 These hints will be visible when you're creating an issue or editing an issue. The only time where they won't be visible is in the preview. as you can see here:
BeFunky-collage
(this is apparently also the method used in other mifos repositories like community-app)

**Comment by luckyman20** [comment]
Change commit title to `doc: comment the hints in issue template`.

**Comment by OussEmaDevCode** [comment]
@luckyman20 Is it going to be merged ?

**Comment by luckyman20** [comment]
@OussEmaDevCode Sorry, I missed it earlier. Thanks for the PR.

**Pull request merged**
