### PR TITLE
Fix for null pointer of progressBar

### LINKED ISSUE #1100: App crashes while fetching data in SI section inside Payments
**Summary:**
App crashes, when opening SI tab under Payments section and then switching to another section suddenly

**Steps to reproduce:**
1. Open Payments section from the bottom navigation bar
2. Open SI section
3. Open Home section by clicking on the home icon on the bottom navigation bar
4. Observe

**Expected behavior:**
Home section should open

**Observed behavior:**
Home sections open, but the app crashes.

**Device and Android version:**
OnePlus 6
Android 10

**Screenshots:**

https://user-images.githubusercontent.com/50913976/103673059-20979280-4fa3-11eb-91cc-a227726a75c5.mp4

**Crash Log:**
[log.txt](https://github.com/openMF/mobile-wallet/files/5771483/log.txt)

### PR DESCRIPTION
**Pull request by divyank00**
## Issue Fix
Fixes #1100 

## Screenshots

https://user-images.githubusercontent.com/50913976/103681989-41b1b080-4fae-11eb-820e-3b8f2f3daee7.mp4

## Description
Made sure that the activity is not null before updating UI

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by divyank00** [comment]
Could also use safe call operator

**Comment by EGOR-IND** [comment]
what is the change now exactly?

**Comment by divyank00** [comment]
> what is the change now exactly?
if (activity!=null)

**Comment by EGOR-IND** [comment]
sorry i just saw the issue right now okay let me check the changes and make a review.

**Review by EGOR-IND — APPROVED** [review]
Seems fine to me.

**Comment by divyank00** [comment]
@devansh-299 @s-ayush2903  Please Review

**Review by devansh-299 — APPROVED** [review]
Nice work @divyank00! Merging this

**Pull request merged**
