### PR TITLE
Updated the badge for dev branch

### LINKED ISSUE #1050: docs: Update CI badges in Readme
**Summary:**
People willing make their initial contributions to project are welcome to fix this issue. Currently, readme file displays old CI badges from latest merge commit from travis CI, but as now we've completely migrated to [GitHub-Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/introduction-to-github-actions) it'll be better if we update the badges there and use GH-Actions ci badges.

**Steps to reproduce:**
Have a look in badges section of [readme](https://github.com/openMF/mobile-wallet#mobile-wallet)

**Expected behavior:**
Should display GH-Actions badges

**Observed behavior:**
Old travis ci badges

What did you see instead?  Describe your issue in detail here.
|Outdated Badges[CI]|
|--|
|travisBadges|
**Device and Android version:**
NA

**Screenshot:**
Attached above

PS: The GH-Actions badges for concerned workflow can be generated from [mobile-wallet actions](https://github.com/openMF/mobile-wallet/actions).

### PR DESCRIPTION
**Pull request by vedpatwardhan**
## Issue Fix
Fixes #1050 

## Screenshots

Screenshot 2020-11-14 at 1 25 10 PM

## Description
Updated the old CI badge for the dev branch by the GH-Actions CI badge in the readme.

##

[ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

[ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

[ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by vedpatwardhan** [comment]
A similar change might also be needed to be done in the readme for the master branch, please guide me on how to do that.

**Comment by devansh-299** [comment]
> 
> 
> A similar change might also be needed to be done in the readme for the master branch, please guide me on how to do that.

@VedPatwardhan for master branch, you need to use the same mark down except that you will have to query **master** branch this time. The markdown is as follows: `.../badge.svg?branch=master)`

After doing this, we will probably get "_No Status_" as no workflows have ran for master branch yet.

**Comment by vedpatwardhan** [comment]
I have done the same for master branch also. 
Do I have to create a new pull request for the same also?

**Review by shiv07tiwari — APPROVED** [review]
Good Job @VedPatwardhan

**Pull request merged**
