### PR TITLE
fix/docs: fixed screenshot orientation error in mobile phones

### LINKED ISSUE #965: Screenshot.md file is not mobile friendly
**Summary:**

the grids that we have used in `Screenshots.md` are not the best way to go about it IMO because we need to make it responsive.

**Steps to reproduce:**

open [this link](https://github.com/OpenMF/mobile-wallet/blob/dev/Screenshot.md) on a mobile device.

**Expected behavior:**

Screenshots should be clearly visible even on phone.

### PR DESCRIPTION
**Pull request by Bhavnaharitsa**
Fixes: #965 
The Screenshot.md file didn't show the screenshots properly when viewed in mobile. In this pull request, I have fixed it.
||||   
|:---:|:---:|:---:|
| |  | 

||
|:---:|

- [.] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [.] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [.] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by rchtgpt** [comment]
Some screens are imperfect sized, I think changing their images would solve our problem. Can you do that?

**Comment by s-ayush2903** [comment]
@Bhavnaharitsa please go through [this patch](https://github.com/openMF/mobile-wallet/wiki/Commit-style-guide#the-type) and please adhere to the qualifiers' significance

**Comment by s-ayush2903** [comment]
@Bhavnaharitsa Please also update the visuals of the screens namely:
* Selecting User Type
* Google SignUp

As both of 'em have old app logo although it doesn't has focus in any of the screens but still, i feel the need of the change as it(old logo) is still visible

**Comment by Bhavnaharitsa** [comment]
> @Bhavnaharitsa Please also update the visuals of the screens namely:
> 
> * Selecting User Type
> * Google SignUp
> 
> As both of 'em have old app logo although it doesn't has focus in any of the screens but still, i feel the need of the change as it(old logo) is still visible

Irrelevant to this pr

**Comment by Bhavnaharitsa** [comment]
> Some screens are imperfect sized, I think changing their images would solve our problem. Can you do that?

Yes yes, also their title is making a huge difference I feel. However the phone from which their screenshot is taken can also make a difference. I'll see what I can to make them size equal:)

**Comment by Bhavnaharitsa** [comment]
@rachittt Please check :)

**Comment by Bhavnaharitsa** [comment]
@shiv07tiwari @devansh-299 Please look into this :)

**Comment by devansh-299** [comment]
@Bhavnaharitsa Google Signup and Home Screen screenshots appear smaller than the rest when viewed on a mobile phone

**Comment by Bhavnaharitsa** [comment]
> @Bhavnaharitsa Google Signup and Home Screen screenshots appear smaller than the rest when viewed on a mobile phone

@devansh-299 , The thing  with tableview is, it adjusts according to the phone we have taken images from. I guess, the screenshots you have mentioned are taken from different phones. And also, I think the upper text is a factor for the space(I'm not sure).

**Comment by rchtgpt** [comment]
Hi @Bhavnaharitsa! Sorry that it took me so long to review the PR. This is a great solution that more or less solves the issue! Thanks a lot for your contributions. Merging it :rocket:

**Pull request merged**
