### PR TITLE
Fix #1180: Progress Dialog doesnot closes after operation finished in…

### LINKED ISSUE #1180: Progress Dialog doesnot closes after operation finished in ReceiptActivity
**Summary:**

Progress Dialog does not closes after operation finished in ReceiptActivity
**Steps to reproduce:**

Have a fresh installation go to the receipt and click on the download button and give storage permission to the app

**Expected behaviour:**

Progress Dialog should close after the operation is finished

**Observed behavior:**

Progress Dialog is not closing after the operation is finished

**Device and Android version:**

Any

**Screenshots:**

https://user-images.githubusercontent.com/54978105/105501659-8053a480-5cea-11eb-99c2-174131cf893e.mp4

### PR DESCRIPTION
**Pull request by ritish099**
… ReceiptActivity

## Issue Fix
Fixes #1180

## Screenshots

https://user-images.githubusercontent.com/54978105/105503692-eb05df80-5cec-11eb-8066-7c399605bbae.mp4

## Description
Fix Progress Dialog Error

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by ritish099** [comment]
@haran2248 kindly review this

**Comment by haran2248** [comment]
Yeah good work!

**Review by haran2248 — APPROVED** [review]

**Comment by divyank00** [comment]
Duplicate of #1117

**Comment by devansh-299** [comment]
@ritish099 nice work but as pointed out by @divyank00 this issue (also a duplicate of #1116 ) is already being addressed by another open PR. Hence closing this

**Pull request closed without merging**
