### PR TITLE
Add error snackbar for transferring money

### LINKED ISSUE #60: Error while transferring money
**Summary:**

When I tried to send money to other random UPI address, it is showing error in Toast ‘Error fetching Receiver’. Firstly, it should be shown in SnackBar and the error should be more clear like ‘Error finding Virtual Payment Address’ and the loader goes off in a infinite loop.

Also, the wallet balance at that time was 0 so my suggestion is that we should first check if balance is enough and then find the receiver.

**Steps to reproduce:**

Keep wallet Balance 0.

Dashboard -> Transfer (Send) -> Enter a Random UPI Address and amount greater than balance (in our case greater than 0)

**Expected behavior:**

The app should firstly search for if balance is enough or not and then if receiver is not find, the error should be shown in a SnackBar with a error message something like `Error finding Virtual Payment Address`.

**Observed behavior:**

The firstly searches for a receiver without taking care of balance. Also, shows the error message in a Toast ‘Error fetching Receiver’.

**Device and Android version:**

Pixel 2 Android Marshmallow (Android Emulator)

### PR DESCRIPTION
**Pull request by m-sameer**
Fixes #60 

Add snackbars for showing:
- Invalid amount transfer
- Insufficient balance
- Error finding Virtual Payment Address
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by ankurs287** [comment]
@m-sameer Did you run ./gradlew check on the terminal?

**Comment by m-sameer** [comment]
I did. It's failing and I don't know why. Could you please help me with that?

**Comment by ankurs287** [comment]
@m-sameer There is some problem in project files. I am merging the PR for now.

**Comment by m-sameer** [comment]
Thanks. :)

**Pull request merged**
