### PR TITLE
Fix #439 - Added share Qr code functionality in ShowQrActivity

### LINKED ISSUE #439: adding sharing feature of qr code generated
**Summary:**

Summarize your issue here.
 
Adding sharing QR code feature would be a great asset to the customer

### PR DESCRIPTION
**Pull request by dubeyaayush07**
Fix #439

Screenrecorder-2020-03-10-18-54

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by dubeyaayush07** [comment]
The PR #441 also addresses the same issue but it had some merge conflicts and there was no activity there for a long time(3 months) also in that pr multiple qr code images were visible in the gallery I solved that issue by storing these images temporarily in the app's cache directory and was able to access the uri with the help of the file provider

**Comment by dubeyaayush07** [comment]
@shiv07tiwari I followed the same post and took the same approach

**Comment by shiv07tiwari** [comment]
Okay, looks good.

**Comment by shiv07tiwari** [comment]
@dubeyaayush07 fix the merge conflict

**Comment by dubeyaayush07** [comment]
@shiv07tiwari  done

**Comment by shiv07tiwari** [comment]
@dubeyaayush07 travis check is failing. Can you look into it

**Comment by dubeyaayush07** [comment]
@shiv07tiwari  fixed the checks

**Pull request merged**
