### PR TITLE
fix: confirmation dialog when passcode forgotten

### LINKED ISSUE #327: Add a confirmation dialog in forgot pin.
**Summary:**

When user clicks on forgot pin, he is directed to login page.

**Expected behavior:**

He should get a confirmation dialog.

### PR DESCRIPTION
**Pull request by shiv07tiwari**
Fixes #327 

53124935-b3331200-3582-11e9-84eb-833b619c68d0

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by shiv07tiwari** [comment]
@luckyman20 Kindly review.

**Comment by naman14** [comment]
Honestly, I don't think this is needed

**Comment by shiv07tiwari** [comment]
@naman14 What changes should I make ?

**Comment by luckyman20** [comment]
@shiv07tiwari change it to something like `Passcode will be reset, are you sure?` not exactly but yeah something like this.

**Comment by shiv07tiwari** [comment]
@luckyman20 Yes we can change the words to "Your passcode will be reset. Are you sure?"

**Pull request merged**
