### PR TITLE
Fix : #1094 Adding a check for root access

### LINKED ISSUE #1094: Feat: Adding a security to check that device has root access or not.
**Summary:**

We can add a security check that the device has root access or not. Because rooted devices are less secure than nonrooted devices for any banking and wallet transaction.

**Expected behavior:**

The user should not get registered if the device has root access.

**Observed behavior:**

We can add a security check for rooted devices.

### PR DESCRIPTION
**Pull request by Harshad09**
## Issue Fix
Fixes #1094 

## Screenshots

image

## Description
fix #1094
Using an open-source library called [rootbeer](https://github.com/scottyab/rootbeer), which performs required checks to detect root access.
These are the current checks/tricks rootbeer are using to give an indication of root.
### **Java checks**

- checkRootManagementApps
- checkPotentiallyDangerousApps
- checkRootCloakingApps
- checkTestKeys
- checkForDangerousProps
- checkForBusyBoxBinary
- checkForSuBinary
- checkSuExists
- checkForRWSystem

### **Usage**

```
RootBeer rootBeer = new RootBeer(context);
if (rootBeer.isRooted()) {
    //we found indication of root
} else {
    //we didn't find indication of root
}
```
### **Dependency**
```
dependencies {
    implementation 'com.scottyab:rootbeer-lib:0.0.8'
}
```

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Harshad09** [comment]
@devansh-299  @s-ayush2903 Can you Please Review my PR

**Comment by devansh-299** [comment]
> 
> 
> @devansh-299 @s-ayush2903 Can you Please Review my PR

@Harshad09 I am not sure whether we need these changes or not. The extra checks do seem good to me personally but I will have to confirm if they are required or not. For now, let's just keep this pull request open. We will get back to this later

**Comment by Harshad09** [comment]
> > @devansh-299 @s-ayush2903 Can you Please Review my PR
> 
> @Harshad09 I am not sure whether we need these changes or not. The extra checks do seem good to me personally but I will have to confirm if they are required or not. For now, let's just keep this pull request open. We will get back to this later

Glad to know that you like this feature I got this idea from Gpay it does the same thing. https://www.howtogeek.com/241012/safetynet-explained-why-android-pay-and-other-apps-dont-work-on-rooted-devices/

**Comment by devansh-299** [comment]
Closing this pull request, please refer [this thread](https://github.com/openMF/mobile-wallet/issues/1094#issuecomment-1207185714)

**Pull request closed without merging**
