### PR TITLE
 fix: added black back arrow

### PR DESCRIPTION
**Pull request by Bhavnaharitsa**
Fixes: #773
Added back arrow in black color in QRActivity

- [.] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [.] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [.] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Bhavnaharitsa** [comment]
Screenshot
Screenshot_20200228-085007_Mifos Pay

**Comment by dubeyaayush07** [comment]
Same problem with SpecificTransactionsActivity, MerchantTransferActivity, LinkBankAccountActivity, BankAccountDetailActivity. Could you modify these too?

**Comment by Bhavnaharitsa** [comment]
Yes sure! +1

**Comment by Bhavnaharitsa** [comment]
@naman14 Please review

**Comment by refactor-droidyy** [comment]
@Bhavnaharitsa already solved #708

**Comment by Bhavnaharitsa** [comment]
@shiv07tiwari Sir, please review!

**Comment by luckyman20** [comment]
Duplicate PR for #702

**Pull request closed without merging**
