### PR TITLE
Fix#1164

### LINKED ISSUE #1164: Useless top magin in the BottomSheet of activity_merchant_transaction.xml
**Summary:**

The margin at the top of bottomSheet of activity_merchant_transaction.xml is creating a bad UI, so tit should be removed.

**Steps to reproduce:**

1. go to Merchant fragment in the,
2. tap on any merchant,
3. Merchant Transaction activity will open,
4. scroll the transaction list and you will an extra portion coming out of bottom sheet.

**Expected behavior:**

That margin should not exist.

**Observed behavior:**

Right now that margin exist.

**Device and Android version:**

VIVO Y83, Android Version = 8.1.1

**Screenshots:**

### PR DESCRIPTION
**Pull request by EGOR-IND**
## Issue Fix
Fixes #1164 

## Description
I removed that margin.

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by EGOR-IND** [comment]
@devansh-299 review this one when you have time:).

**Review by devansh-299 — APPROVED** [review]
Nice find @EGOR-IND, merging this

**Comment by EGOR-IND** [comment]
> Nice find @EGOR-IND, merging this

Thanks for merging all these PRs today @devansh-299, it really feels good when someone merges your PR,  you made my day devansh, once again thanks😄.

**Comment by devansh-299** [comment]
> 
> 
> > Nice find @EGOR-IND, merging this
> 
> Thanks for merging all these PRs today @devansh-299, it really feels good when someone merges your PR, you made my day devansh, once again thanks😄.

Thank you for the contributions 🎉, can relate to the joy of getting one's pull request merged xD

**Pull request merged**
