### PR TITLE
Fix:#679 Share payment receipt feature along with file added

### LINKED ISSUE #679: Feature Request: Adding option to share transaction receipt
**Summary:**

A user should be provided with the functionality to download and share the receipts of their transactions. This feature can prove useful in informing other concerned parties about the completion of a transaction .

**Steps to reproduce:**

* Go to Payments ->History tab
* Select any transaction -> View Receipt
* Here this functionality can be added

**Device and Android version:**

Xiaomi PocoF1
Android9
StockRom

### PR DESCRIPTION
**Pull request by haran2248**
## Issue Fix
Fixes #679 

## Description

This is an extension of pull request #1141 
Share receipt feature has been added with file sharing and downloading

Uploading WhatsApp Video 2021-01-08 at 14.24.42.mp4…

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by divyank00** [comment]
Duplicate of #1142

**Comment by haran2248** [comment]
> Duplicate of #1142

I had made a PR of this in #1141 but accidentally I accidentally squashed more than the required number of commits this is just a modified version of that,The file sharing has been implemented in this as well,But in #1142 the function for intializing download and sharing is the same.Which might cause problems

**Comment by divyank00** [comment]
I would suggest you to delete this PR because its a duplicate of #1142.
Best of Luck

**Comment by haran2248** [comment]
> I would suggest you to delete this PR because its a duplicate of #1142.
> Best of Luck

Yeah im deleting this

**Comment by devansh-299** [comment]
> 
> 
> > I would suggest you to delete this PR because its a duplicate of #1142.
> > Best of Luck
> 
> Yeah im deleting this

Closing this pull request

**Pull request closed without merging**
