### PR TITLE
kotlin mifospay LoginActivity

### LINKED ISSUE #1363: Migration to Kotlin : LoginActivity
**Summary:**
Migration to Kotlin : `LoginActivity`

**Steps to reproduce:**
Convert java code to kotlin

### PR DESCRIPTION
**Pull request by zaidazaize**
#1363

## Issue Fix
Fixes #1363 

## Description
1. Converted LoginActivity file from Java to kotlin
2. Added viewBinding to Login Activity
3. Performed Kotlin cleanup

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by zaidazaize** [comment]
hey @devansh-299 can you review my pull request

**Review by rchtgpt — CHANGES_REQUESTED** [review]
Hi @zaidazaize, your approach looks good to me. Can you please resolve the merge conflicts?

**Comment by zaidazaize** [comment]
I have performed the rebase of this branch in order to resolve the conflict.

**Comment by zaidazaize** [comment]
@rchtgpt do let me know if any changes are required

**Comment by rchtgpt** [comment]
> @rchtgpt do let me know if any changes are required

Although, rebasing the branch itself solves the issue, this isn't the cleanest approach since it adds all the previously committed changes to your PR's change tracking files—hence the 18 commits and 32 changed files.

I suggest you:
1. Create a new branch
2. Make sure it is up to date with the `origin/dev` branch
3. Make the Java to Kotlin migration changes on that branch
4. Send a Pull Request from that branch

If your final pull request has more than 1 commit, make sure to squash them into a single commit.

**Pull request closed without merging**
