### PR TITLE
feat: alert dialog box for log out button

### LINKED ISSUE #564: Pressing logout button should open alert dialog box
**Summary:**

Pressing logout should open an alert dialog box asking for confirmation of user to logout

**Steps to reproduce:**

Go to Settings and press the log out button

**Expected behavior:**

It should open an alert dialog box asking for user confirmation to log out

**Observed behavior:**

Immediate log out from the app
**Device and Android version:**

Android 9
Redmi Note 5 pro
MIUI 11

**This issue is for GCI Students**

### PR DESCRIPTION
**Pull request by rachittt**
Fixes #564 

Working GIF:
ezgif com-video-to-gif (1)

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by rachittt** [comment]
@govinddixit can you please review it :)

**Comment by GOVINDDIXIT** [comment]
LGTM 👍

**Comment by rachittt** [comment]
@luckyman20 all right, I'll change that.

**Comment by luckyman20** [comment]
Also, push these changes to dev branch not to master.

**Pull request closed without merging**
