### PR TITLE
 Added null otp entered error and Added Offline profile pic Functionality 

### PR DESCRIPTION
**Pull request by Vipinsoni38**
Fixes #{Issue Number}

Please Add Screenshots If any UI changes.

Please Add Summary of what changes you have made.(Optional)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by RajaVamsi11** [comment]
@Vipinsoni38 First please make an issue and make a PR resolving that issue. In that way, it seems easy to manage a project.

**Comment by Vipinsoni38** [comment]
Okay! currently working on squashing commits

**Comment by RajaVamsi11** [comment]
@Vipinsoni38 Fix the Travis error also.

**Comment by Vipinsoni38** [comment]
actually i also added the local image upload for the app 

maybe that code gave travis error will resolve it soon

**Comment by RajaVamsi11** [comment]
@Vipinsoni38 As you see there are 2 commits of @naman14 included in this PR. Can you please resolve that.

**Comment by Vipinsoni38** [comment]
Working on that

**Comment by Vipinsoni38** [comment]
@RajaVamsi11 well is the problem with dev branch beacuse
That branch is 2 commits behind master.

**Pull request closed without merging**
