### PR TITLE
fix:There should be a limit of 4 digits on changing Passcode in Edit Profile

### LINKED ISSUE #300: There should be a limit of 4 digits on changing Passcode in Edit Profile
**Summary:**

There should be a limit of 4 digits on changing Passcode in Edit Profile, since the app only allows a 4 digit pin to be entered while opening the app

**Device and Android version:**

Realme 2 Pro
Android version 8.1.0

**Screenshots:**

screenshot_2019-02-13-17-01-39-73 1

### PR DESCRIPTION
**Pull request by shaliniv16**
Fixes #300 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

### CODE REVIEW

**Comment by shaliniv16** [comment]
@luckyman20 please review.

**Comment by luckyman20** [comment]
Push your changes `dev` branch.

**Comment by naman14** [comment]
@shaliniv16 Can you also add validation checks regarding the same in UI. The passcode should be of exactly length 4

**Comment by naman14** [comment]
Also, rebase to `dev`

**Pull request closed without merging**
