### PR TITLE
fix: added all the screenshots of app

### PR DESCRIPTION
**Pull request by Bhavnaharitsa**
Fixes: #661
Added screen shots of the app
- [.] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [.] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [.] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Bhavnaharitsa** [comment]
@luckyman20 @shiv07tiwari @naman14 Please review

**Comment by Bhavnaharitsa** [comment]
@luckyman20 Please review this because as soon as this gets merged, I can add the link on Readme.

**Comment by luckyman20** [comment]
@Bhavnaharitsa Please add screenshots as how would README will look finally.

**Comment by Bhavnaharitsa** [comment]
Sure, will!

**Comment by Bhavnaharitsa** [comment]
image

image


image

image

image

**Comment by Bhavnaharitsa** [comment]
@luckyman20 these are screenshots. But, this is not how README will look. Once, this gets merged, we can have a link on GitHub which I will paste on README under the screenshots section

**Comment by shiv07tiwari** [comment]
Merging this. Please add the link @Bhavnaharitsa

**Pull request merged**
