### PR TITLE
fix: #1187 Added Image cropper for images taken through camera in pro…

### LINKED ISSUE #1187: Add image cropper for picture taken from camera
**Summary:**

Theres no image cropper for image taken by camera

**Steps to reproduce:**
1. Open profile
2. Click on the profile picture
3. Select camera
4. Capture image
5. Confirm
6. Observe

**Expected behavior:**
A cropper should appear as it appears for image taken from gallery

**Observed behavior:**
Image directly added to profile

**Device and Android version:**
OnePlus 6
Android 10

**Screenshots:**

https://user-images.githubusercontent.com/50913976/106235429-a6180680-6220-11eb-910b-a71500610f4b.mp4

### PR DESCRIPTION
**Pull request by divyank00**
## Issue Fix
Fixes #1187

## Screenshots

https://user-images.githubusercontent.com/50913976/106242134-38260c00-622d-11eb-9bc6-62f7e30ee4c0.mp4

## Description
Added the cropper after capturing image from camera

##

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by divyank00** [comment]
@devansh-299 Can you please review it

**Review by EGOR-IND — APPROVED** [review]
Looks good and when my PR for enhancement in camera crop specifications gets accepted then together it'll look excellent. You can see PR #1176 if you don't know which PR i'm talking about:).

**Comment by divyank00** [comment]
@devansh-299 have a look😊

**Comment by devansh-299** [comment]
> 
> 
> @devansh-299 have a look😊

will review it as soon as I can

**Review by devansh-299 — APPROVED** [review]

**Pull request merged**
