### PR TITLE
fix : Alphabetical order in Linked bank acccounts list

### LINKED ISSUE #393: Alphabetical order is missing in Linked bank accounts
**Summary:**

Alphabetical order is missing in Linked bank accounts list.

**Steps to reproduce:**

Open app Home --> Finance --> Accounts 

**Expected behavior:**

Linked bank accounts list should be alphabetically sorted.

**Observed behavior:**

Linked bank accounts list is not alphabetically sorted.

**Device and Android version:**

Device: Redmi 4
Version: 7.1.2

**Screenshots:**

screenshot_2019-03-02-19-45-18-357_org mifos mobilewallet mifospay

### PR DESCRIPTION
**Pull request by RajaVamsi11**
Fixes #393 

**Screenshots** 
screenshot_2019-03-02-19-48-36-972_org mifos mobilewallet mifospay
screenshot_2019-03-02-19-48-54-570_org mifos mobilewallet mifospay

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by manddy** [comment]
@RajaVamsi11 Does it matter if we have an alphabetical order in that page? .If a user links a bank account it should appear first then the other ones linked after that and so on .

**Comment by RajaVamsi11** [comment]
@manddy I am thinking that it will be easy to navigate for the user if the bank accounts are in sorted order.

**Comment by manddy** [comment]
@RajaVamsi11  I don't think Andhra bank above Hdfc is gonna make a lot of difference in terms of UI/UX

**Comment by RajaVamsi11** [comment]
@manddy I just referenced from the #376  and #355 and thought it would be nice to add this feature in linked bank accounts also. Let's wait for the review of mentors.

**Comment by luckyman20** [comment]
@RajaVamsi11 Please push your changes to `dev` branch.

**Comment by devansh-299** [comment]
Closing this because of inactivity. @RajaVamsi11 you can create a new PR to `dev` branch

**Comment by luckyman20** [comment]
Closing this because of inactivity.

**Pull request closed without merging**
